### ISSUE TITLE
unable to login with admin user and password after restarting the couchdb

### ISSUE THREAD

**Issue by cuddle-sujeet** [apache/couchdb#1079]
## Expected Behavior
After restarting CouchDB, the authentication should be successful with the correct credential.

## Current Behavior
after installation and first-time setup, I was able to login to fauxton and create documents.
but after quitting CouchDB and then restarting it, when tried to log in it failed, stating wrong username or password. I pretty sure that the credential is correct, but still this authentication is failing.

## Your Environment

* Version used: CouchDB 2.1.1
* Browser Name and version: chrome Version 63.0.3239.84 
* Operating System and version (desktop or mobile): Mac high Sierra 10.13.1
* Link to your project:

**Comment by cuddle-sujeet** [comment]
Got the solution:
The problem is that I used a capital letter as username eg: Testadmin.
But CouchDB changes this to all small letter testadmin, hence I was unable to log in.
I verified by looking at /Users/$user/Library/Preferences/couchdb2-local.ini file where I saw the admin username

Always use the small letters for DB name and username.

**Comment by Souravrao-31** [comment]
I tried small letter username still incorrect.

**Comment by wohali** [comment]
Can you try upgrading to a newer CouchDB build? We don't support 2.1.1 anymore.

At least use the 2.3.1 installer, if not the 3.0.0.

Also, this is not a bug, because if it was, we'd have heard of it by now.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
