### ISSUE TITLE
Replicator infinite failure loop

### ISSUE THREAD

**Issue by Avaq** [apache/couchdb#1081]
## Expected Behavior

No matter the circumstances, the `_changes` feed should accept incoming connections in under 30 seconds.

## Current Behavior

When supplying a `filter` argument to the `/db/_changes` end-point (filtered replication), the connection is not accepted until a document in the database passes the filter. This causes connections to drop (due to `replicator.connection_timeout`) on large datasets with only few documents matching the filter.

## Possible Solution

It is trivial to ask: so why don't I just increase the value for `replicator.connection_timeout`? This is how I've circomvented the issue thus far. But it's not a complete solution because of several reasons:

* The replicator clients are managed by third-parties. It's not easy to get all of them to increase the timeout consistently. When one party fails to do so, they ruin it for all other parties (See Context).
* Increasing the replication timeout will only work for a limited amount of documents. As the amount of documents in my database increases, the chance that the new timeout is not long enough also increases.

A permanent solution seems very simple to me; CouchDB should already start sending heartbeats *while* it's filtering changes, preventing the connection from timing out while it's working on a response. Connections should only time out if the actual connection to the server could not be established.

## Steps to Reproduce

1. Prepare a database. Note that this filter *simulates* a large dataset by blocking for two seconds on every document. The alternative would be to insert hundreds of thousands of documents, which produces the same behaviour.

```shell
curl -X PUT localhost:5984/replication-source
curl -X PUT localhost:5984/replication-source/_design/test -d '{"filters":{"test":"function(){var future = Date.now() + 2000; while(Date.now() < future){}; return false}"}}'
for i in {1..20}; do curl -X POST -H 'Content-Type: application/json' localhost:5984/replication-source -d '{"foo":"bar"}'; done
```

2. Test the behavior

```shell
curl 'localhost:5984/replication-source/_changes?since=0&filter=test/test&heartbeat=2000'
```

3. On CouchDB 1.6, this behaves correctly. The server immediately responds with `{"results":[`, followed by a newline every two seconds. On CouchDB 2.x, the request times out without any response.

## Context

In my case, connections drop *consistently*, which means the replication *target* never receives any documents, as the replication is re-initiated every thirty seconds using the same sequence number. But worse, the replication *source* gets overloaded because it's continuously filtering the same large set of data. This causes other clients to also start losing connections due to the increased load on the server, which in turn increases the load, et cetera.

## My Environment

* Version used: `2.1`
* Browser Name and version: `curl 7.57.0 (x86_64-pc-linux-gnu) libcurl/7.57.0 OpenSSL/1.0.2n zlib/1.2.11 libssh2/1.8.0 nghttp2/1.24.0`
* Operating System and version: `Linux 4.9.68 #1-NixOS SMP Sat Dec 9 21:01:57 UTC 2017 x86_64 GNU/Linux`
* Secondary operating System and version: `Darwin 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

## Personal Plea

This bug is causing an otherwise beautiful key business application that synchronises data over many low-bandwidth off-shore nodes to fail. It's of great personal interest to me to get it fixed. If somebody could point me to the relevant piece of source code, I wouldn't mind having a go at resolving the issue via a pull-request.

**Comment by Avaq** [comment]
This regression bug is still causing me a lot of manual labour on a daily basis. Any advice will be much appreciated. I'm considering downgrading the server to version 1.x.

**Comment by nickva** [comment]
Hi Avaq,

Thanks for your report.

Noticed in the test behavior script you specified a heartbeat. In 2.x replicator doesn't use hearbeats, instead it uses timeouts:

https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_api_wrap.erl#L486

Notice that it uses a timeout for the changes feed and the value of the timeout is 1/3 of the `connection_timeout`. By default connection timeout is 30s so the timeout for the _changes feed ends up being 10s.

Try re-running test script with a timeout parameter specified instead instead of a heartbeat. 

I just tested it a few days ago investigating a similar issue in 2.1.x and noticed that server responds quickly with a `results` and periodic newlines are being sent, keeping the connection alive. In my case I was also looking at a continuous change feed (because the replication was a continuous one as well). Wonder if there is a difference in behavior between a continuous and a normal one in respect to filters. 

Besides the timeout vs heartbeat, and continuous vs normal, a few more questions to get a better idea of what's happening:

 * To double check, is the replication itself running on a 2.x cluster? What are the versions of the targets and source? Are they all 2.x as well?

 * Are there any proxies or load balancers involved and do you think they could affect the connections?

 * How many replication jobs are running? CouchDB 2.x uses a scheduling replicator with a default maximum number of jobs set to 500. If there are more than 500 some tasks will be stopped and some started periodically. In case of filtered replications, with large source db and a restrictive filter, like you have, replications won't checkpoint unless they receive a document update via the filter. However if it takes too long and the job is swapped out by the scheduler, it might not have  chance to checkpoint, it will be stopped. Next time starts will use 0 for the changes feed start 0, and it will wait again, not get a document, will be stopped, etc. In this case you can try for example to increase max_jobs to a number high enough to fit all the replications jobs you have.

**Comment by Avaq** [comment]
Hi @nickva, thank you for your response!

> Noticed in the test behavior script you specified a heartbeat. In 2.x replicator doesn't use hearbeats, instead it uses timeouts

I didn't know heartbeats were removed. It doesn't really matter for my case though. The only reason I'm specifying a heartbeat in my tests is to make the result more visual (so you don't have to wait ten seconds using 1.6 to see if something is happening). 

I have adjusted my test.

```sh
# We create our test database
curl -X PUT localhost:5984/replication-source

# We insert a design doc with a filter function that is guaranteed to take long
# The reason is so we can simulate a database with a lot of documents which are
# not going to pass in the filtering process.
curl -X PUT localhost:5984/replication-source/_design/test -d '{"filters":{"test":"function(){var future = Date.now() + 2000; while(Date.now() < future){}; return false}"}}'

# We insert a bunch of documents so that filtering them will take time. Note
# that I increased the number from 20 to 100, because I have more CPU cores
# this time around (I didn't consider that before).
for i in {1..100}; do curl -X POST -H 'Content-Type: application/json' localhost:5984/replication-source -d '{"foo":"bar"}'; done
```
```sh
# I send a request for changes to the database. This request resembles the request
# a replication client might send very closely.
curl 'localhost:5984/replication-source/_changes?feed=normal&style=all_docs&since=0&filter=test%2Ftest&timeout=10000'
```

I'm getting better results now. I do indeed see the `{"results":[`-line printed after about ten seconds, followed by a periodic newline, until finally returning the last sequence number. Unfortunately, this is not what's happening on the production environment, but these results are a huge step forward! Thank you.

> To double check, is the replication itself running on a 2.x cluster? What are the versions of the targets and source? Are they all 2.x as well?

There is once "central server" to which, and from which, a large number of clients push and pull subsets of information. The server runs a 2.x cluster, and the clients are single-node CouchDB instances ranging between version 1.6 on Windows XP and 2.x on Windows 10.

> Are there any proxies or load balancers involved and do you think they could affect the connections?

The central server sits behind an nginx reverse proxy, which is now my prime suspect. Thank you for pointing this out to me.

> How many replication jobs are running?

There are a few replication jobs running within the central server itself, but they do not cause problem. At any given time, some fifty clients running their own replication jobs will be polling the server for changes.

> In case of filtered replications, with large source db and a restrictive filter, like you have, replications won't checkpoint unless they receive a document update via the filter. However if it takes too long and the job is swapped out by the scheduler, it might not have chance to checkpoint, it will be stopped. Next time starts will use 0 for the changes feed start 0, and it will wait again, not get a document, will be stopped, etc.

This sounds a lot like what I thought was happening, but every node only runs two replication jobs. One for upstream replication, and one for downstream. Neither are continues.

----

I will be investigating whether nginx might be buffering the response before sending it along, causing connection to drop.

**Comment by Avaq** [comment]
:man_facepalming: https://www.nginx.com/resources/admin-guide/reverse-proxy/#buffers

**Comment by Avaq** [comment]
I just added `proxy_buffering off;` to my nginx configuration and I already tested it. It solved all of my problems. Thank you so much for taking the time to think about my problem! Sorry for taking your time.
