### ISSUE TITLE
CouchDB 2.1.1: Compaction daemon - unable to calculate free space for `/run/user/0`: `enoent`

### ISSUE THREAD

**Issue by jvegaseg** [apache/couchdb#1097]
We have a 6-node cluster and we receive this warning in one of the servers (only in one).

CouchDB software was installed through packages (yum install) on  virtualized Centos 7 servers using OpenVZ 7.

Output of **df -h**:

```
S.ficheros        Tamaño Usados  Disp Uso% Montado en
/dev/ploop23569p1   9,9T    72G  9,4T   1% /
none                 31G      0   31G   0% /sys/fs/cgroup
none                 31G      0   31G   0% /dev
tmpfs                20G      0   20G   0% /dev/shm
tmpfs                20G   144K   20G   1% /run
tmpfs               4,0G      0  4,0G   0% /run/user/0
```

Any clue about this warning?
That means that compactation fails?

Regards,

**Comment by wohali** [comment]
Can you share the exact line from `couch.log` please? Thanks.

**Comment by jvegaseg** [comment]
Of course:

```
[warning] 2018-01-14T03:30:37.531777Z couchdb@185.13.60.120 <0.263.0> -------- Compaction daemon - unable to calculate free space for `/run/user/0`: `enoent`
[warning] 2018-01-14T03:35:37.710059Z couchdb@185.13.60.120 <0.263.0> -------- Compaction daemon - unable to calculate free space for `/run/user/0`: `enoent`
```

**Comment by jvegaseg** [comment]
Today, Zabbix has reported "**Free swap space in % (X.X.X.X:system.swap.size[,pfree]): 0 %**"

Each machine has 100 Gigas of swap space (and 40G of RAM). They need more swap space?

**Comment by jvegaseg** [comment]
Any clue about "unable to calculate free space for `/run/user/0`: `enoent`"

**Comment by wohali** [comment]
Sure sounds like you ran out of memory.

The `/run` file system is virtualised as a temporary filesystem, meaning it runs out of a ramdisk. On my system, that's potentially about 800MB of RAM:

```
$ df -h /run
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           801M  2.2M  799M   1% /run
```

For the load you're placing on your cluster, it sounds like your machines need more RAM. You could add swap in a pinch, but ideally I'd start by doubling the RAM on the machine. Also, it is best if your CouchDB nodes are not running any other processes (except for basic monitoring and system maintenance). For instance, move your web server and application servers to different machines.

**Comment by jvegaseg** [comment]
Each node has 40 GIGAS of RAM:
```
 free -h
              total        used        free      shared  buff/cache   available
Mem:            40G        244M        112K        1,3M         39G         36G
```

```
df -h
S.ficheros        Tamaño Usados  Disp Uso% Montado en
/dev/ploop23569p1   9,9T   276G  9,2T   3% /
none                 31G      0   31G   0% /sys/fs/cgroup
none                 31G      0   31G   0% /dev
tmpfs                20G      0   20G   0% /dev/shm
tmpfs                20G   144K   20G   1% /run
tmpfs               4,0G      0  4,0G   0% /run/user/0
```


And we are using only 3 databases.

I was not expecting that CouchDB requires so much memory.

Thanks,

**Comment by wohali** [comment]
Can you share your `local.ini` or any changes to CouchDB config please? thanks.

**Comment by jvegaseg** [comment]
Some logs with debug activated:

```
[debug] 2018-01-21T19:48:26.334147Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for view group `_auth` (database `shards/50000000-5fffffff/_users.1510390507`) is 0%, estimated space for compaction is 51 bytes.
[debug] 2018-01-21T19:48:26.335236Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/50000000-5fffffff/_replicator.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.336555Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/50000000-5fffffff/grabaciones.1510391138` is 9%, estimated space for compaction is 45813786228 bytes.
[debug] 2018-01-21T19:48:26.336936Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/50000000-5fffffff/_global_changes.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.338248Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/50000000-5fffffff/pruebas.1510391087` is 48%, estimated space for compaction is 1973958 bytes.
[debug] 2018-01-21T19:48:26.338866Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/30000000-3fffffff/_users.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.339851Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/30000000-3fffffff/_replicator.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.341106Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/30000000-3fffffff/grabaciones.1510391138` is 8%, estimated space for compaction is 45798847378 bytes.
[debug] 2018-01-21T19:48:26.341834Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/30000000-3fffffff/_global_changes.1510390507` is 87%, estimated space for compaction is 91708 bytes.
[warning] 2018-01-21T19:48:26.342346Z couchdb@185.13.60.120 <0.241.0> -------- Compaction daemon - unable to calculate free space for `/run/user/0`: `enoent`
[info] 2018-01-21T19:48:26.342923Z couchdb@185.13.60.120 <0.32222.0> -------- Starting compaction for db "shards/30000000-3fffffff/_global_changes.1510390507"
[debug] 2018-01-21T19:48:26.343025Z couchdb@185.13.60.120 <0.8153.1> -------- Compaction process spawned for db "shards/30000000-3fffffff/_global_changes.1510390507"
[debug] 2018-01-21T19:48:26.351314Z couchdb@185.13.60.120 <0.210.0> -------- New task status for <0.8153.1>: [{changes_done,2},{database,<<"shards/30000000-3fffffff/_global_changes.1510390507">>},{progress,100},{started_on,1516564106},{total_changes,2},{type,database_compaction},{updated_on,1516564106}]
[notice] 2018-01-21T19:48:26.364450Z couchdb@185.13.60.120 <0.32222.0> -------- Compaction swap for db: ./data/shards/30000000-3fffffff/_global_changes.1510390507.couch 356558 53448
[info] 2018-01-21T19:48:26.365003Z couchdb@185.13.60.120 <0.32222.0> -------- Compaction for db "shards/30000000-3fffffff/_global_changes.1510390507" completed.
[debug] 2018-01-21T19:48:26.366648Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/30000000-3fffffff/pruebas.1510391087` is 27%, estimated space for compaction is 1806452 bytes.
[debug] 2018-01-21T19:48:26.367095Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/10000000-1fffffff/_users.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.368076Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/10000000-1fffffff/_replicator.1510390507` is 0%, estimated space for compaction is 4248 bytes.
[debug] 2018-01-21T19:48:26.369259Z couchdb@185.13.60.120 <0.241.0> -------- Fragmentation for database `shards/10000000-1fffffff/grabaciones.1510391138` is 9%, estimated space for compaction is 44659295380 bytes.
```

**Comment by jvegaseg** [comment]
Here you have local.ini:

```
[cluster]
q = 16

[log]
level = warning
```

Installation is default installation with packages: yum install xxx

**Comment by wohali** [comment]
Can you let us know how much RAM all of your CouchDB-related processes are consuming? Show the output of `top` or `atop`. Are you running any other processes on the machines?

Do these databases have attachments? If so you are likely running into apache/couchdb#745.

**Comment by jvegaseg** [comment]
Output of top command:

```
top - 22:45:21 up 18 days, 9 min,  1 user,  load average: 0,01, 0,03, 0,05
Tasks:  37 total,   1 running,  36 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,1 us,  0,0 sy,  0,0 ni, 99,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 41943040 total,    55716 free,   281676 used, 41605648 buff/cache
KiB Swap:  5242880 total,  5159660 free,    83220 used. 38393832 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                               
 9067 couchdb   20   0 2727464 257012   2964 S   1,3  0,6   2825:26 beam.smp                                                                                                              
24512 root      20   0  141660   5432   4172 S   0,0  0,0   0:00.03 sshd                                                                                                                  
  940 root      20   0  517020   4756   1316 S   0,3  0,0   7:31.89 fail2ban-server                                                                                                       
  854 root      20   0  221880   4384   2720 S   0,0  0,0   0:41.04 httpd                                                                                                                 
   85 root      20   0   45020   4124   4000 S   0,0  0,0   0:02.41 systemd-journal                                                                                                       
  107 root      20   0  253080   3516   1544 S   0,0  0,0   0:36.20 rsyslogd                                                                                                              
  106 root      20   0  234428   2880   1988 S   0,0  0,0   0:02.05 firewalld                                                                                                             
17268 apache    20   0  221880   2752   1084 S   0,0  0,0   0:00.00 httpd                                                                                                                 
    1 root      20   0   43176   2688   1864 S   0,0  0,0   0:53.95 systemd                                                                                                               
24529 root      20   0  155488   2044   1472 R   0,3  0,0   0:00.03 top                                                                                                                   
24514 root      20   0  115392   1984   1604 S   0,0  0,0   0:00.00 bash                                                                                                                  
  889 zabbix    20   0   83808   1668   1572 S   0,0  0,0   4:39.71 zabbix_agentd                                                                                                         
  857 root      20   0  105996   1504   1400 S   0,0  0,0   0:00.01 sshd                                                                                                                  
  105 root      20   0   24204   1376   1228 S   0,0  0,0   0:17.51 systemd-logind                                                                                                        
  104 dbus      20   0   24412   1268   1080 S   0,0  0,0   0:36.68 dbus-daemon                                                                                                           
 9112 couchdb   20   0    9516   1208   1084 S   0,0  0,0   0:00.28 sh                                                                                                                    
  893 zabbix    20   0   84228   1192    980 S   0,0  0,0   2:19.82 zabbix_agentd                                                                                                         
  890 zabbix    20   0   83932   1172   1040 S   0,0  0,0   1:51.71 zabbix_agentd                                                                                                         
  891 zabbix    20   0   83932   1172   1040 S   0,0  0,0   1:51.21 zabbix_agentd                                                                                                         
  892 zabbix    20   0   83932   1172   1040 S   0,0  0,0   1:50.63 zabbix_agentd                                                                                                         
  112 root      20   0   22644    928    832 S   0,0  0,0   0:01.32 crond                                                                                                                 
   94 root      20   0   41412    868    864 S   0,0  0,0   0:00.00 systemd-udevd                                                                                                         
  884 root      20   0   88688    820    644 S   0,0  0,0   0:26.69 sendmail                                                                                                              
  110 root      20   0    6456    628    624 S   0,0  0,0   0:00.00 agetty                                                                                                                
  111 root      20   0    6456    628    624 S   0,0  0,0   0:00.00 agetty                                                                                                                
  932 smmsp     20   0   84124    560    420 S   0,0  0,0   0:00.28 sendmail                                                                                                              
 9113 couchdb   20   0    4300    560    500 S   0,0  0,0   0:03.40 memsup                                                                                                                
  883 zabbix    20   0   83808    420    384 S   0,0  0,0   0:00.00 zabbix_agentd                                                                                                         
 9116 couchdb   20   0   11544    300    284 S   0,0  0,0   0:00.00 inet_gethost                                                                                                          
 9114 couchdb   20   0    4300    268    268 S   0,0  0,0   0:00.00 cpu_sup                                                                                                               
 9117 couchdb   20   0   11544    260    244 S   0,0  0,0   0:00.00 inet_gethost                                                                                                          
  881 root      20   0   24992    236    236 S   0,0  0,0   0:00.00 xinetd                                                                                                                
 9075 couchdb   20   0   11580    212    200 S   0,0  0,0   0:07.04 epmd                                                                                                                  
  116 root      20   0   71788    204    200 S   0,0  0,0   0:00.00 saslauthd    
```

Yes, database has only documents with attachments. I do not see replication errors mentioned in apache/couchdb#745.

**Comment by adrienverge** [comment]
We experience the same problem: lots of free disk space, lots of free RAM, and:

```
[notice] 2018-03-06... -------- Compaction swap for db: /var/lib/couchdb/shards/00000000-1fffffff/my_db.1493304636.couch 131313 45297
[warning] 2018-03-06... -------- Compaction daemon - unable to calculate free space for `/run/user/0`: `enoent`
[notice] 2018-03-06... -------- Compaction swap for db: /var/lib/couchdb/shards/00000000-1fffffff/my_db.1493304645.couch 131266 45250
```

None of these DBs have attachments. Actually the issue doesn't seem related to attachments, but instead to the fact that `/run/user/0` doesn't exist:

```shell
# ls -a /run/user 
.  ..  1000
```

@wohali Can you open the issue again?

**Comment by wohali** [comment]
OK. Adding to the 2.2.0 milestone as well.

**Comment by janl** [comment]
The problem here is that Erlang’s disksup module doesn’t nicely play with all the special file systems that Linux seems to keep gaining (I lost track a while ago).

This time it is `/run/user/0` that fails to have an `{fs,ls}tat()` run on it and that bubbles up to the compaction daemon that has to loop through all mount points to match the one where `[couchdb] database_dir` is located, to check for available space to decide whether it is safe to compact.

We could try and start adding an exclusion list, but that will require maintenance. We could start and try be more clever handling `file:get_link_info()` errors, but that too seems error prone. This is a harmless warning too, maybe we can demote this to `debug` level?

**Comment by janl** [comment]
sorry, misread the code a bit, we could change it so that the error isn’t fatally stopping the compaction daemon.

**Comment by wohali** [comment]
It'd be much better if we could simply check the free space for the volume on which the shard resides, rather than scanning all volumes for free space first. I did a bunch of research when it became clear to me this isn't an easy problem to solve.

Reminder: [we've been here before](https://github.com/apache/couchdb/issues/732), which is when we [introduced this warning](https://github.com/apache/couchdb/pull/803).

First stop: python, since I feel they have excellent cross-platform support for this kind of thing. A simplified [code excerpt of finding the mount point for a given file's path](https://stackoverflow.com/questions/4453602/how-to-find-the-mountpoint-a-file-resides-on):

```
def find_mount_point(path):
    path = os.path.abspath(path) # or os.path.realpath()
    while not os.path.ismount(path):
        path = os.path.dirname(path)
    return path
```

Erlang has `filename:absname/1` and `filename:dirname/1`, but it doesn't have an `os.path.ismount` equivalent, so I dug into how Python implements this. Of course, there are different implementations for [POSIX](https://github.com/python/cpython/blob/3460198f6ba40a839f105c381f07179aba1e8c61/Lib/posixpath.py#L187-L220), [Mac](https://github.com/python/cpython/blob/3460198f6ba40a839f105c381f07179aba1e8c61/Lib/macpath.py#L118-L122) and [Windows](https://github.com/python/cpython/blob/3460198f6ba40a839f105c381f07179aba1e8c61/Lib/ntpath.py#L246-L275), with the Windows implementation requiring [a call out to a Win32 function](https://github.com/python/cpython/blob/6921e73e33edc3c61bc2d78ed558eaa22a89a564/Modules/posixmodule.c#L3830-L3877) because Windows treats local drives, UNC paths, network-mounted drives and junction points (symlinks) all differently.

We also need to be mindful of the difference between `abspath` and `realpath`, i.e. when a relative path symlink is a parent directory; ascending up the tree can lead to misleading results if a true absolute path isn't determined in the process. `filename;absname/1` doesn't attempt to deal with this problem. Amusingly, [mochiweb has solved this particular problem](https://github.com/mochi/mochiweb/blob/b7f3693a9008de6d31a67174f7184fe24093a1b4/src/mochiweb_util.erl#L72).

For comparison, I checked JS/node/npm, and found [diskusage](https://www.npmjs.com/package/diskusage) which appears to be the most popular solution to this problem. It, too, calls out to a Win32 API endpoint on Windows and relies on `statvfs` for POSIX.  (It's not clear that this module's Win32 implementation actually handles all the different possibilities that the Python implementation does, incidentally.)

**Option 1**: implement all of the above. The Windows NIF is ugly, but there are other reasons we might want to go down the path of a Windows-only util NIF anyway. I can help here if this is desired.

Next stop, rabbitmq, as a fairly mature Erlang server-thing that definitely does disk space checking. They use a much lower tech alternative, namely, [shelling out and running cli commands to check free space for a given path](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_disk_monitor.erl#L211-L237). Unfortunately, this is problematic, too: there have been [a](https://stackoverflow.com/questions/17148510/rabbitmq-strange-disk-free#17944684) [few](https://groups.google.com/forum/#!topic/rabbitmq-users/LLnyb_MXa6Q) bugs and [multiple](https://github.com/rabbitmq/rabbitmq-server/commit/43fe62ef15465ad01c73dd7f591c7659b5d2d307) [fixes](https://github.com/rabbitmq/rabbitmq-server/commit/4eaa46ef0ea1e1777c86a5ddc93e0cf447a3f448) [required](https://github.com/rabbitmq/rabbitmq-server/commit/186c32700b52de68cb3ba71e445844d236519603). A comment is made in the that StackOverflow link that this parsing is fragile, and could easily be broken by locale-specific changes, too; `df -kP` guarantees POSIX-compatible output, but there's no guarantee we'll get any sort of consistent report out of Windows without switching to [a PowerShell implementation](https://stackoverflow.com/questions/12159341/how-to-get-disk-capacity-and-free-space-of-remote-computer#12159479) or the aforementioned Win32 API call.

**Option 2**: Use the rabbitmq approach and shell out to the system rather than parsing paths and calling `disksup:get_disk_data/0` once we find a mount point we can use to match against Erlang's gathered stats. This feels easier (no NIF!), but the devil's in the details, and technically speaking, rabbitmq's implementation is [MPL](https://github.com/rabbitmq/rabbitmq-server/blob/master/LICENSE), which is a ["Category B" weak-copyleft license](https://www.apache.org/legal/resolved.html#category-b). We could probably write to the rabbitmq people and get them to waive the MPL on this particular part of code, or we could white-box our own implementation.

**Option 3**: Blacklist a bunch of paths that we know are bad: `/proc`, `/run`, `/dev`. I hesitate to say all `tmpfs` volume types on Linux, because running Couch out of a `tmpfs` volume as an all-in-memory CouchDB (prior to PSE landing) isn't unreasonable. That said, if the `*stat*` calls fail on a `tmpfs` volume, we still need to recover gracefully. @janl and I don't like this because it's yet another weird thing to maintain with magic values.

**Option 4**: Do the least possible. Stay with the current approach and just don't crash out when we can't stat a particular volume. If we can't actually get the free space for the guessed mount point for the current volume, punt per #803 and try our best anyway, free space or no. We'll probably end up with more bugs like this in the future if we do this, but it'll let us close out this bug quickly ;)

**Comment by janl** [comment]
I’d say we go for 4 now with the variant that we still fail if we can’t get the free space for the `database_dir` volume. And keep Options 1/2 for later.

**Comment by janl** [comment]
forgot to say: outstanding analysis
