### ISSUE TITLE
Misleading API HTTP Status Codes

### ISSUE THREAD

**Issue by jasonrogena** [apache/couchdb#1112]
Just noticed that some status codes returned by the API are misleading:
 1. Adding a configuration using [` PUT /_config/{section}/{key}`](http://docs.couchdb.org/en/2.0.0/api/server/configuration.html#put--_config-section-key) returns the status code 200 (instead of 201) when the configuration is created. 200 is OK, but could mean one of two things in this scenario (the config was created or the config already exists). It would be better if 201 was returned if the config was created, and 200 if the config already (with the provided value) already exists.
 2. If a database already exists and you use ['PUT /{db}'](http://docs.couchdb.org/en/2.0.0/api/database/common.html#put--db), returns the status code 412 (instead of 409). Using 412 in this scenario is entirely misleading. If using the HTTP spec, the first thought that comes to mind is that one of the request headers is incorrect.

Not sure what motivated the project to go with these status codes. They are, however, a bit vague when used in those contexts (and hence might be misleading).

**Comment by wohali** [comment]
paging @rnewson who may be able to shed some light on the 412 vs. 409 distinction.

**Comment by rnewson** [comment]
That decision predates my involvement with the project. I agree that 412 is being used inappropriately as 412 is for when a request has If-Match, If-None-Match or If-Unmodified-Since headers and one of them evaluates to false. 409 would be more appropriate.

OP is also correct on appropriate use of 201 vs 200 for PUT /_config. 201 is correct for resource creation, 200 for update.

There are more issues with the HTTP API than these. It's unclear if we should address them given the decade or so that CouchDB has behaved this way. I doubt we'll see changes here any sooner than the planned (but not scheduled) replacement of mochiweb for something more modern.
