### ISSUE TITLE
should_create_delete_database_continuously (100 times) fails on Jenkins CI

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1122]
The test seems to have started failing after #1062 landed (/cc @eiri @nickva).

I beg you to not ignore Jenkins :)

## Expected Behavior
Test runs should be green across the board

## Current Behavior
8 of 11 runs in Jenkins timed out on this test in the last run on `master`

https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/46
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/47
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/48
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/56
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/55
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/50
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/52
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/173/pipeline/51

## Possible solution
FYI the semantics of the test changed with the PR. See:

https://github.com/apache/couchdb/blob/e81c54e32d2a165dc762ad4217b753da723dc1fa/src/couch/test/couch_db_tests.erl

vs. 

https://github.com/apache/couchdb/blob/master/src/couch/test/couch_db_tests.erl#L129-L139

We are calling `couch_server:delete()` now; previously we were calling `couch_db:close()` which only de-monitors the DB.

**Comment by eiri** [comment]
No, the test actually been calling `couch_db:delete/2` inside `cycle`, inside `loop`, inside `_assert,` inside `timeout`, inside a list comprehension - [right here](https://github.com/apache/couchdb/blob/e81c54e32d2a165dc762ad4217b753da723dc1fa/src/couch/test/couch_db_tests.erl#L127). It just hard to see because the thing been rather convoluted. 

The semantics didn't changed, we are still calling same `couch_db:create/2`, `couch_db:close/1` (inside `create_db` helper) and then `couch_server:delete/2` inside `delete_db` helper repeatedly. 

What changed is wrapping `?_test` that ensure that we are not ignoring failures in preparation stages, i.e. that initial db creation or in between asserts, I suppose that's how it was passing before. I'll look into this.

**Comment by wohali** [comment]
Thanks, I'm not great at reading Erlang code.

I appreciate you taking a look!
