### ISSUE TITLE
[enhancement] Populate `info` for running replications in `/_scheduler/docs`

### ISSUE THREAD

**Issue by garbados** [apache/couchdb#1159]
Currently, /_scheduler/docs does not populate the `info` object for running replications ([source](https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_scheduler.erl#L139-L147)) such that in order to track a replication's progress, one must still check /_active_tasks periodically. /_scheduler/docs should populate `info` for active replications so that their progress can be tracked without checking /_active_tasks.

## Expected Behavior

The `info` object on running replication tasks should not be `null` where possible. It should contain properties like `docs_read` that can normally be acquired from /_active_tasks.

## Current Behavior

The `info` property is only populated for replication tasks that have completed or failed.

## Context

I am trying to track a running replication's progress by using /_scheduler/docs rather than /_active_tasks.

## Your Environment

* Version used: 2.1.1
* Browser Name and version: curl 7.47.0
* Operating System and version (desktop or mobile): Ubuntu 16.04.3 LTS
* Link to your project: N/A

**Comment by wohali** [comment]
ping @nickva

**Comment by nickva** [comment]
This is a good idea still. Not sure what stats to put in the info. Everything from _active_tasks seems too much...? Maybe mostly the stats (whatever would be saved on replication completion)?

Code-wise would need to have a mechanism to save last stats from a replication job when it completes and then to carefully re-initialize the stats when job continues to run such that counters are not reset back to 0.

Technically it is a breaking API change as well, but not in a terrible way since perhaps returning `null` was kind of a place-holder more detailed info in the future.

**Comment by nickva** [comment]
We fixed this, info for running jobs is now populated. There is not need to ever check _active_tasks for replication jobs

```
            "info": {
                "changes_pending": null,
                "checkpointed_source_seq": 0,
                "doc_write_failures": 0,
                "docs_read": 1,
                "docs_written": 1,
                "missing_revisions_found": 1,
                "revisions_checked": 1,
                "source_seq": "2-g1AAAACNeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQiQ1L9____szKYExlygQLsBuYGycYWSSkMnKV5KalpmXmpKTg157EASYYGIPUfagYT2IykpGQTk5QUTF1ZAODIJHo",
                "through_seq": "2-g1AAAACNeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQiQ1L9____szKYExlygQLsBuYGycYWSSkMnKV5KalpmXmpKTg157EASYYGIPUfagYT2IykpGQTk5QUTF1ZAODIJHo"
            },
```
