### ISSUE TITLE
Replication between 2 databases stuck

### ISSUE THREAD

**Issue by rynobrits1** [apache/couchdb#1288]
I am replicating documents between 2 databases on the same server, it has been stuck on 46% for the last few days

## Current Behavior
Replication does not progress it will stay on the same amount of checkpointed source sequence

## Steps to Reproduce (for bugs)
I have deleted the document from the database and re-entered it, it will stay in triggered state with no errors in the logs. Checkpointed source sequence 257043, current source sequence 557413, progress 46%. I have restarted the service and server multiple time it would just go up  to the same state it was.

## Your Environment

* Version used: 1.6.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows Server
* Link to your project:

**Comment by wohali** [comment]
Hi @rynobrits1 , please provide any logs you may have that can help diagnose the problem.

**Comment by janl** [comment]
Closing this issues because there won‘t [be any more CouchDB 1.x releases](https://lists.apache.org/thread.html/6fa798e96686b7b0013ec2088140d00aeb7d34487d3f5ad032af6934@%3Cdev.couchdb.apache.org%3E). If you experience this issue on current 2.x releases, please re-open it with additional information.
