### ISSUE TITLE
Fix "Bulk Documents Transaction Semantics" section in the documentation (v2.1.1)

### ISSUE THREAD

**Issue by mguimas** [apache/couchdb#1317]
In the "Bulk Documents Transaction Semantics" section in the documentation, a phrase begins with "The two modes are:", but only one mode is described (see section [here](http://docs.couchdb.org/en/2.1.1/api/database/bulk-api.html#bulk-documents-transaction-semantics)).

This phrase must be fixed to something like "The single mode is:", or the missing mode must be described.

**Comment by wohali** [comment]
Hi @mguimas , thanks for your report. Can you reopen this please on https://github.com/apache/couchdb-documentation ? We'd also appreciate a pull request over there if you would like to help improve our docs.

Thanks again for your interest in Apache CouchDB!

**Comment by wohali** [comment]
Hi @mguimas , 

This has been fixed already for our upcoming 2.2.0 release:

https://github.com/apache/couchdb-documentation/pull/216

You can see this live already here:

http://docs.couchdb.org/en/latest/api/database/bulk-api.html#bulk-documents-transaction-semantics

Due to the invariant nature of our release labels on the documentation repository, we are unable to change the labelled documentation for an existing release at this time.

**Comment by mguimas** [comment]
OK thanks!
