### ISSUE TITLE
couchdb returns 500 to elasticsearch river changes query

### ISSUE THREAD

**Issue by krishnakode** [apache/couchdb#1332]
We have couchdb on 0.11.0 and elastic search on 0.90.3. When I add a river on elasticsearch for the couchdb, couch throws the below error. Elastic logs show a socket timed out error. What might be causing this error? and, How to fix it?

[error] [<0.3416.6>] Uncaught error in HTTP request: {error,{case_clause,{error,enotconn}}}
[info] [<0.3416.6>] Stacktrace: [{mochiweb_request,get,2},
             {couch_httpd_external,json_req_obj,3},
             {couch_query_servers,filter_docs,5},
             {couch_changes,'-make_filter_fun/3-fun-1-',5},
             {couch_changes,changes_enumerator,2},
             {couch_btree,stream_kv_node2,8},
             {couch_btree,stream_kp_node,7},
             {couch_btree,fold,4}]

* Version used: couchdb 0.11.0, elastic 0.90.3
* Browser Name and version: chrome
* Operating System and version (desktop or mobile): Linux 2.6.26-2-xen-686

**Comment by wohali** [comment]
Hi @krishnakode  I'm so sorry... we no longer support CouchDB 0.11.0. Not only that, Elasticsearch doesn't support the CouchDB river plugin [since 2015](https://github.com/elastic/elasticsearch-river-couchdb), either.

The `enotconn` error means that the external process was unable to connect correctly. Beyond that I can't be of any more help.

You would do best to join, then email our mailing list, user@couchdb.apache.org, for advice on migrating from 0.11 to the latest 2.1.1 release.
