### ISSUE TITLE
Proxy bug in 2.1.1: httpd_global_handlers {couch_httpd_proxy, handle_proxy_req,..}

### ISSUE THREAD

**Issue by johs** [apache/couchdb#1407]
Configuring a proxy like this in 2.1.1 will fail:
 
    [httpd_global_handlers]
    _google = {couch_httpd_proxy, handle_proxy_req, <<"http://www.google.com">>}

## Expected Behavior
As described in http://docs.couchdb.org/en/2.1.1/config/proxying.html
The proxy handler should map a pathname and pass all content after that prefix through to the configured proxy address.

## Current Behavior
The proxy handler, in this example _google, will just return an error as if it was a database name:

    {"error":"unauthorized","reason":"You are not authorized to access this db."}

first, then after login

    {"error":"not_found","reason":"Database does not exist."}

## Port 5986 not a workaround

According to Endy Jasmi in https://github.com/apache/couchdb/issues/1054:
"Currently, after I have set the httpd_global_handlers, the proxy is working on port 5986 but not working on port 5984."

However, the port can be used in rewrite. Sending a Host header in the rewrite function (like  headers:{ 'Host': 'http://localhost:5986/' } ) will not work.

## Context

Proxy handler is essential for using the new rewrite function in design documents. Using rewrite functions enables advanced routing as apposed to the old static rewrite rules, and the global handler for proxy is a vital part of this. 

## Your Environment

* Version used: 2.1.1
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): OSX and Ubuntu

**Comment by janl** [comment]
I’ve had a detailed look at this, and the reason this wasn't ported (other than this feature being on the deprecation path) was that chttpd doesn’t have a way to load routes from runtime configuration. The design of `chttpd` also makes this an unlikely addition.

What *would be possible* is re-hooking up the old handler in a new way (so the feature would be exist again, but it’d be configured differently). E.g. we could do a new config section:

```
[chttpd_proxy]
endpoint = "http://example.com"
```

The way this would work then is a static URL like `/_proxy/:endpoint` for all requests, but you could configure `:endpoint`, but not `_proxy` which you could do before.

I believe that would still satisfy the requirements for this feature, however:

1. This approach wouldn’t be backwards compatible to 1.x. Since bringing this feature back is about restoring that compatibility is the whole point, we miss that point.

2. This whole feature is slated to be deprecated for 3.0, so I’m hard pressed to add any code that will be relatively short lived and deprecated on introduction.

3. I realise it is convenient to just run CouchDB somewhere and have it be the sole piece of infrastructure needed, but these days it is very simple to spin up a proxy server in front of CouchDB in whatever environment you need (haproxy, nginx, [g]unicorn, node.js etc.pp.), so at least there is a workaround.

4. Adding a BC-preserving version of this would mean a significant addition to `chttpd` that I don’t see anyone adding, or if proposed, willing to maintain.

Therefore, I propose to mark this as a documentation error, we should have announced it’s removal on the release of 2.0.0. As we’ve missed this, we should follow suit quickly.
