### ISSUE TITLE
Improve plugin architecture / Erlang release building

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1515]
Out of trying to improve how you can ship things like full text or geo support, @davisp stated he had some good ideas around how to improve our plugin architecture. I can't find any notes anywhere, so this gets a new roadmap issue.

**Comment by wohali** [comment]
@davisp mentions:
>Improved Erlang Release Building
>It'd be nice to have something in the build system that allowed for custom combinations of Erlang applications to be used in the release (Erlang definition, not ASF). This would be useful for our "popular configurations" that @janl mentioned (ie, Dreyfus/Clouseau and GeoCouch being examples).

**Comment by kocolosk** [comment]
I don't think this belongs in 3.x. We closed #1516 by way of #2037, and I don't think anyone is signing up to better integrate Geospatial ahead of 3.0.

**Comment by wohali** [comment]
@davisp what do you think? I expect this was only in here for #1516 but if you had other ideas, I'd at least like to see a writeup of what you want to do before we move it out of 3.x.

**Comment by wohali** [comment]
ping @davisp for thoughts. I'm ok with moving this out of 3.x but I'd like at least a pointer to the way forward for whomever picks this up in the future.

**Comment by davisp** [comment]
Fine by me to move this out of 3.0.

In terms of what I was thinking about for this sort of work it was basically to take this blog post [1] and make it a not terrible experience.

However, given that we're pushing towards providing better binaries for everyone I could just as well see us having various pre-built binaries that include some of the major extra bits like search or geo or what not. Which is to say that maybe creating various flavor builds might be a replacement for trying to work up a whole Erlang release config/tooling thing?

[1] https://developer.ibm.com/dwblog/2015/text-search-apache-couchdb/

**Comment by kocolosk** [comment]
Adding Dreyfus to CouchDB went a very long way towards eliminating that blog post. Most of the rest of the work is on Clouseau packaging, which is outside this project.

**Comment by davisp** [comment]
Hah! Totally forgot that we added dreyfus which sure does remove most of the thorny bits that I was worried about. And I'd agree that the Clouseau side of things is outside CouchDB.

Works for me as good enough for 3.0 certainly.

**Comment by nickva** [comment]
Dreyfus is now part of https://docs.couchdb.org/en/stable/install/search.html#install-search

There is also a new search implementation available in main https://github.com/apache/couchdb/blob/4c76b38a2184c327d6173ffba438db95bc6b96b6/nouveau/README.md. The plan as of the latest Apache CouchDB dev meeting is to release it as part of the next 3.4 release with the jar file available in the package. Users would have to install their own JDK.

Geo has been removed and unsupported by Cloudant for a while now. There are some remnants mentioning "hastings" in `main` but otherwise nobody is testing or actively running Geo from what I am aware.
