### ISSUE TITLE
_users:  status 403 "You are not allowed to access this db."

### ISSUE THREAD

**Issue by greenais** [apache/couchdb#1556]
I'm not sure if it's expected behaviour but I didn't find any traces of such requiremet in docs/issues. 

_users db created, several users in it with roles "stranger" and "registered",
require_valid_user = true in config.
In Fauxton in _users I can see default _admin in Member Roles.

## Current Behavior
Once I fire GET {{server}}:{{port}}/_users/org.couchdb.user:john (with john's credentials, off cause) 
I've got 
error: 'forbidden',
reason: 'You are not allowed to access this db.',
status: 403,

When I add john's "registered" role to Member Roles in _users db - everything works as expected, I can get doc.

## Expected Behavior
Shouldn't user get user doc he owned (according to docs) without need of specifying his role in _users Member Roles?

## Your Environment

* Version used: 2.1.1
* Postman 6.2.4
* Windows 8.1

**Comment by wohali** [comment]
@greenais Did you change the `_security` object on the `_users` database? That is unsupported.

**Comment by greenais** [comment]
@wohali Yes. otherwise user couldn't access his own doc from _users db, getting 403 error above. 
Btw, in docs I can't find anything about any resctrictions of modifying _security doc for _users, only _auth is locked, is that right?

**Comment by wohali** [comment]
You're right, this is an oversight in the documentation. I've opened an issue to track this: apache/couchdb-documentation#317

In short:
1. Do not change the `_security` object on the `_users` database. We don't recommend changing it, and the consequences are on you.
1. The expected behaviour for `_users` is that, once you have created a server-level admin user (taking CouchDB out of Admin Party), any user can view and edit their own `_users` database document, and cannot view or edit any other user's database document. The full list of rules is here: http://docs.couchdb.org/en/stable/intro/security.html#authentication-database
1. Don't treat `_users` as a "proper" CouchDB database; it is handled specially and not everything you can do to a regular database can be done to `_users`.
1. A future release will prevent you from changing the `_users` database's `_security` object, and also remove any reason to do so, as the DB itself will only be accessible through API logic - see #1534 
1. A full rework of CouchDB's security model is coming in the 3.x-ish timeframe, see #1504.

**Comment by greenais** [comment]
@wohali Thank you for comprehensive answer, I wil take care of not changing _security in _users anymore.
But question remains - why in my setup CDB was blocking user from accessing his own doc in _users?
I created _users DB via API (under Node) quite long ago and I'm in doubt if after that _admin role was there originally in Member Roles. Could you please check it in your Fauxton? Perhaps I added it myself on some stage for some reason, not sure..
FYI: I removed all Users/Roles from Members section in Fauxton - and now it works as intended, no 403 errors anymore. So the root of issue was that _admin in Roles. 
Probably it's a really good idea to block admins from modifying _security object as it leads to such side effects, you are right.

**Comment by wohali** [comment]
@greenais After running a brand new test 2.2.0 node, here's what I see:

```bash
$ curl http://root:password@localhost:15984/_users/_security
{}
```

**Comment by greenais** [comment]
@wohali Thank you. 
It's my fault, clearly.
