### ISSUE TITLE
Range values in query to complex key view seem to be ignored

### ISSUE THREAD

**Issue by greenais** [apache/couchdb#1565]
I query view with complex (array) keys with intention to perform partial search, but get wrong results. Probably I'm doing something wrong, but I can't figure out what it is - according to docs it should work.

## Expected Behavior
Query should return zero rows

## Current Behavior
when I fire: 
`{{server}}:{{port}}/search/_design/search/_view/firstLast?startkey=["Mar","Fru","female","Argentina","Buenos Aires"]&endkey=["Mar\u9999","Fru\u9999","female","Argentina","Buenos Aires"]`
I get:
```
"total_rows": 18,
    "offset": 4,
    "rows": [
        {
            "id": "chicho",
            "key": [
                "Mariano",
                "Frumboli",
                "male",
                "Argentina",
                "Buenos Aires"
            ],
            "value": null
        }
    ]
```

which is wrong since index record obviously contans "male".
Seems like third and following values in startkey/endkey are being ignored?
I tried to replace \u9999 with z etc but with avail - same wrong results

## Your Environment
* Version used: 2.1.1
* Postman
* Windows 8.1

**Comment by greenais** [comment]
UPD:
I changed emited secuence of values in key to be [gender, country, city, firstName, lastName] and now gender value in query is respected (as it's "static", not "range").

But I've found out that it seems like only first "range" value is respected - i.e. if I fire:
`startkey=["male","Argentina","Buenos Aires","Mar","Fru"]&endkey=["male","Argentina","Buenos Aires","Mar\u9999","Fru\u9999"]`
it returns all records starting with Mar in firstName, disregarding requirement for Fru in lastName in query.
Is that expected behaviour?

**Comment by wohali** [comment]
Indexes work closer to the way you say in your follow-up post. If you want to limit by gender, country, and city, those items must be _first_ in your compound key. However, the remaining items are just sorted by ICU order, so anything that falls inbetween `["male","Argentina","Buenos Aires","Mar","Fru"]` and `["male","Argentina","Buenos Aires","Mar\u9999","Fru\u9999"]` *alphabetically* will match. This will include `["male","Argentina","Buenos Aires","Mar123","Jan"] because it sorts (by ICU sort order) inbetween the two keys you've provided. You can't provide what you are suggesting as a prefix limitation on the sub-keys, sorry.

You may also want to look at [Mango Indexes](http://docs.couchdb.org/en/stable/api/database/find.html) as an alternative to doing this with JS views. You may find them easier to use (though you will still need to create multiple indexes to achieve what you want). Note that using the operators such as "$regex" will cause a full table scan. You will want to investigate partial indexes to achieve what you desire, assuming you know up front you will always want to do sub-searches under known values of various keys.

The other option is full-text search with clouseau/dreyfus, but this is challenging to setup and install right now.

**Comment by greenais** [comment]
@wohali 
Thank you, now it's completely clear.

**Comment by greenais** [comment]
Partial indexes unfortunately won't help much since they should be pre-defined, but we don't know upfront what string we should filter for.

As for multiple indexes I can't see how they could help, as, for instance, if we have for firstName and lastName: Aar(on) Abd(ubakir) - it will narrow output of $gte just a little bit, leaving there everything until Z anyway.
So the only reliable way to implement .startsWith filtering is to do it programmaticaly on all (potentially huge) query output, I see.

Thank you again for clarification.

**Comment by wohali** [comment]
`startswith` best option is full-text Lucene based search via clouseau and dreyfus. Unfortunately it requires recompiling CouchDB from source + JDK6 to deploy at present.
