### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by jliu1970** [apache/couchdb#1707]
When querying a view using db.queryview api, intermittently, the api returns SocketTimeoutException: Read timed out
## Expected Behavior

In a 6 cpu/2G RAM server with ~90K documents (individual document size is small, <1k bytes),  when a view is queried, 
the view result shall return
## Current Behavior

Intermittently, the api returned SocketTimeoutException: Read timed out.
When looked at couchdb log, we noticed a couple of logs around that time frame:

1. Update index started (in some cases, for a ~90K document database, the index took more than 30 seconds)
2. Compaction started (in some cases, compaction seems to start frequently)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 
* Browser Name and version:
* Operating System and version (desktop or mobile): coreOS
* Link to your project:

[couchdb-short.log](https://github.com/apache/couchdb/files/2542676/couchdb-short.log)

**Comment by wohali** [comment]
This is not a CouchDB bug.

You have five options:

1. Using the `stale=ok` option to querying your view, the response will not wait for the view to finish building.
1. Improve system performance (faster CPU, more RAM, HDD --> SSD --> NVMe)
1. Force index updating ASAP on a cronjob or similar so that when queries are made to the view, it is already built
1. Delay compaction so that it only occurs outside of application usage hours. Put the setting in your `local.ini` file, [here is the documentation in `default.ini`](https://github.com/apache/couchdb/blob/master/rel/overlay/etc/default.ini#L457-L533).
1. Consider moving to [Mango](http://docs.couchdb.org/en/stable/api/database/find.html) from JavaScript views, as these do not require an external process and are much faster than their equivalent JS view.

**Comment by jliu1970** [comment]
Thanks for the recommendations, Joan.
Jimmy
