### ISSUE TITLE
[Feature Request] - Disable compaction ability in configuration

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#1753]
It would be nice to have a configuration that disables completely the compaction feature. In some cases, the application might want to rely on previous versions and even though CouchDB is not meant for that, it would expand its "features" and use cases.

I am not familiar with the code but I imagine that disabling a functionality using a configuration variable should be easy to implement. Correct me if I'm wrong...

**Comment by janl** [comment]
You can disable autocompaction by setting `[compaction_daemon] _default=` to an empty string

**Comment by natcohen** [comment]
@janl Well...I was not talking about auto compaction but was referring to prevent compaction from running in ANY circumstances (including a trigger from an admin). A message would show up to alert that this functionality is disabled. Without this, I would not rely on previous versions if this can't be configured.

Does that make sense?

**Comment by wohali** [comment]
A modification of this nature can be performed directly in the source with recompilation. It doesn't make sense for us to implement this as a new feature, I agree with Jan.

If you can't trust your admins, you've got bigger problems...

**Comment by sureshvv** [comment]
Will specifying 100% for db-fragmentation disable compaction for the db?

**Comment by roelarents** [comment]
The `_default` option is under `compactions` [in the (2.3.1) docs](https://docs.couchdb.org/en/2.3.1/config/compaction.html#compactions). So i think it should be `[compactions] _default` instead of `[compaction_daemon] _default`. Which would make sense. No schedules to run means: run never.

It seems to work for me so far. (Unless there is maybe a hidden default and it will start around midnight again or something, I haven't waited that long yet.) I also tried putting `[]` instead of an empty string by the way, which started a compaction immediately after restart.

My/our use case was that I don't want an automatic compaction to start (for a while), because it seemed to slow down a running replication (230 GiB DB with 46,000,000 docs).

**Comment by ParkSeungwon** [comment]
Compaction configuration seems to have changed in 3.2.
How can I disable auto compaction in couchdb version 3.2?
