### ISSUE TITLE
Startup script breaks relative paths

### ISSUE THREAD

**Issue by natevw** [apache/couchdb#1757]
## Expected Behavior

In CouchDB 1.x, I was able to use configuration like 

```
[couchdb]
database_dir = local_data/databases
view_index_dir = local_data/databases

[log]
file = local_data/logs/couch.log
```

and the daemon would find files relative to the startup path.

I could configure a local repository with it's own CouchDB instance, start it with `couchdb -a local_data/couch.ini` and it would find everything relative to the launch directory.

## Current Behavior

Now the `couchdb` startup script includes this logic:

```
COUCHDB_BIN_DIR=$(cd "${0%/*}" && pwd)
# …
cd "$COUCHDB_BIN_DIR/../"
```
As a result, any relative paths passed in the command line (e.g. `COUCHDB_ARGS_FILE`) or in the config files themselves tends to cause crashing and general upset.

## Possible Solution

Is there a particular reason that this `cd` is now required? I'd be willing to try fix this but don't want to experiment much if there's now a subtle requirement for a particular working directory throughout the system now.

## Context

Forcing absolute paths everywhere means that after bootstrapping the configuration, a developer will be unable to relocate the project/repo, lest they break the now-hardcoded paths to the configuration and log/database storage. With CouchDB 1.x this was not an issue.

**Comment by wohali** [comment]
@natevw The problem comes down to the search path for the embedded Erlang we use in our release process to find all of its libraries. This is a break from CouchDB 1.x where the system Erlang was used; in 2.x releases include their own Erlang runtime and need no OS-level Erlang installed.

We do work around this limitation over in the `dev\run` script for development instances, but it requires a copious amount of `-pa` flags to the `erl` binary, see https://github.com/apache/couchdb/blob/master/dev/run#L420-L449 for the gory details.

Due to max argument limitations esp. on Windows the cd makes things a lot easier at the very least; I don't know if absolute paths are strictly required.

If you want to experiment with this and put up a PR, we'll certainly consider it for inclusion. Be sure to alter `couchdb.cmd` as well as `couchdb` when you make your PR or it'll be rejected. ;)

**Comment by wohali** [comment]
@natevw Ah, there are some other subtle problems, yes.

The defaults for the database_dir and view_index_dir assume the cwd is the root dir:

```
[couchdb]
uuid =
database_dir = ./data
view_index_dir = ./data
```

These obviously won't work if the cwd for the entire app isn't its root directory. So now you're talking about having to fix the entire `rebar`-based release process.

The entire point of the new release process was to create a completely relocatable CouchDB installation...

**Comment by natevw** [comment]
Ah, I see. So basically it's a tradeoff between supporting paths relative to the user's `$PWD` vs. supporting paths relative to the startup script's `$ROOTDIR`.

Seems like build-couchdb made a relocatable installation in the CouchDB 1.x era, but maybe it hardcoded the directory paths or something? Been awhile…

Feel free to close then if you feel it's appropriate.
