### ISSUE TITLE
Cloudant couchDb view still including unwanted id keys outside from the DOC

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1836]
when querying couchdb, it is still sending bad formatted array of objects :

https://jose:windsurf@1c54473b-be6e-42d6-b914-d0ecae937981-bluemix.cloudant.com/footballers/_design/footballers/_view/football?include_docs=true

i only want this :

```
[
{mydoc1content},
{mydoc2content}
]
```

And it currenlty gives me this :

```
[
{id:1,value:1:key:1;doc:{mydoc1content}},
{id:2,value:2:key:2;doc:{mydoc2content}}
]
```

How to only get the docs ? not the unwanted id, key and docs values ?
I think it is called 'metadata', how to get rid of theses unwanted stuffs ? It blocks me from developping further things.

I can't use it with angularjs cause it send badly formatted array of json, please help me.

this is my map fonction 
```
function (doc) {
  emit(doc._id, 1);
}
```

**Comment by popojargo** [comment]
1. Github issues are for bugs only. If you have questions, you can use the mailing list, Slack or StackOverflow
2. You can't only the docs by querying the views. It's designed this way. You mentioned Angular. You can probably query the view and format the data the way you want it. Otherwise, there's always Mango queries that returns an object like this: {docs: [docs....]}
