### ISSUE TITLE
v2.3 binary on bintray

### ISSUE THREAD

**Issue by satazor** [apache/couchdb#1849]
I didn't followed the template because this is more of a question.

Is there any ETA for when the 2.3 release binaries will be made available in the regular CouchDB package repositories?

Thanks!

**Comment by wohali** [comment]
It's there, and has been since the date we announced the release:

http://apache.bintray.com/couchdb/mac/2.3.0/
http://apache.bintray.com/couchdb/win/2.3.0/
http://apache.bintray.com/couchdb-deb/pool/C/CouchDB/
http://apache.bintray.com/couchdb-rpm/el6/x86_64/
http://apache.bintray.com/couchdb-rpm/el7/x86_64/

What are you looking for that you aren't able to find?
