### ISSUE TITLE
The $or operator in _find makes the queries very slow

### ISSUE THREAD

**Issue by fungiboletus** [apache/couchdb#1852]
I would like to use the `$or` operator in _find, but it is surprisingly very slow.

## Expected Behavior
Great performances thanks to the indexes.

## Current Behavior
The indexes seem ignored when the selector uses the `$or` operator.

## Possible Solution
?

## Steps to Reproduce
I have a test database with about 10 000 documents.

A simple `GET /{database}/{id}` is pretty fast and the latency is mostly due to the network (45ms).

A simple `POST /{database}/_find` is also fast, with an acceptable overhead (65ms) and the `total_docs_examined` is 1.

```json
{
  "selector": {
    "_id": "abc"
  },
  "limit": 1,
  "execution_stats": true
}
```

Now, when I use the `$or` operator, things goes slower (~2s) and `total_docs_examined` is quite high depending on the id I query (often around ~1000).

```json
{
  "selector": {
    "_id": {
      "$or": [
        "abc"
      ]
    }
  },
  "limit": 1,
  "execution_stats": true
}
```

I tried to different syntax with the same result:

```json
  "selector": {
    "$or": [
      {
        "_id": "abc"
      }
    ]
  }
```

```json
  "selector": {
    "_id": {
      "$or": [
        {
          "$eq": "abc"
        }
      ]
    }
  },
```

Interestingly, I get  the following warning `"warning": "no matching index found, create an index to optimize query time"` but when I create an index on the `_id`, the warning goes away but it's even slower (~4s) 
```json
{
   "index": {
      "fields": [
         "_id"
      ]
   },
   "name": "id-json-index",
   "type": "json"
}
```

## Context
I would like to query the database using the `$or` operator while keeping good performances.  The querying on the `_id` field is just as an example here, I couldn't fetch the database using many requests to simulate the same behaviour with good performances client side. The following request is an example of a request that would be cumbersome to do client side, especially with pagination.

```json
{
  "selector": {
    "a": "example",
    "b": { "$or": [1,2,3]},
    "c": { "$or": [1,2,3]},
    "d": { "$or": [1,2,3]}
  }
}
```

## Your Environment
[Official Docker `couchdb` image](https://github.com/apache/couchdb-docker/blob/ce1679b4c1312203df2af8936c367c7027d2e888/2.3.0/Dockerfile).
Cluster of 3 CouchDB nodes deployed in a Kubernetes cluster.

**Comment by fungiboletus** [comment]
Thanks for the help.

I tested with the request and index you suggested, and while the `total_docs_examined` looks correct, the performances are still relatively poor (many seconds). I tested a  `_find` with dates comparison returning a similar number of documents,  and a `_bulk_get` and they both run instantly.

**Comment by willholley** [comment]
To expand on @garrensmith's description,`_find` is only able to perform a single index scan per query. If the selector can be mapped to a direct lookup on the index (i.e. you have a predicate which maps exactly to a key in the index) then your query performance will be roughly proportional to the number of documents that match that key in the index; it will still need to load each matching document and evaluate the selector against them before returning a result.

In the case of a disjoint `$or` such as:

```
"selector": {
        "$or": [
            { "director": "George Lucas" },
            { "director": "Steven Spielberg" }
        ]
}
```

an index on `"director"` would be used in preference to a full database scan because it only includes documents containing a `"director"` field. However, the query planner doesn't narrow the keyrange down to the minimal values (which you can verify by looking at the `"mrargs"` field in the explain plan which lists the startkey/endkey used); it just performs a full index scan, opening every document referenced by the index and testing them individually against the selector. The performance of the query is therefore approximately proportional to the number of documents in the index.

In the case that you have different fields referenced within the `$or` predicate, the same logic applies except it will scan the primary index (`_all_docs`) instead.

Regarding optimisation, the thing I would look at is execution stats - whether there's a significantly larger number of documents scanned than matches returned. For static queries, you may be able to improve matters using a [partial index](https://docs.couchdb.org/en/2.3.0/api/database/find.html#find-partial-indexes) to perform the filtering at indexing time rather than query time. For dynamic queries you may need to look at the [text indexes extension](https://developer.ibm.com/dwblog/2015/text-search-apache-couchdb/) which uses Lucene indexes and has rich support for multi-dimensional queries (e.g. using `$or` with multiple complex predicates).

**Comment by fungiboletus** [comment]
> `_find` is only able to perform a single index scan per query.

I see, it makes sense now. Do you think this may change in the future ?

I do need dynamic queries, and the indexes extensions looks promising. However I feel a bit inconfortable patching couchdb to add such feature. Also, having to maintain the indexes outside of CouchDB makes my system more complex and less resilient in my humble opinion.

**Comment by wohali** [comment]
@fungiboletus CouchDB has always required you to create your own indexes, whether using the Mango query syntax or the older JavaScript MapReduce engine.

Unfortunately, at the moment packaging and licensing considerations make it impossible for us to directly provide you binaries with the text index extension built in. Improving this for the future is definitely on the table, see #1515 and #1269.

Remeber you can use the `/{db}/_explain` endpoint to determine whether or not an index has been used for a given query.

As the situation has been explained well enough, and we have tickets for the requested work, I'm closing this bug for now.

**Comment by fungiboletus** [comment]
Alright, thanks for your great explanations. It's appreciated.
