### ISSUE TITLE
CouchDB with couchjs - CouchHTTP documentation

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb#1896]
couchjs is part of CouchDB's query server and it doesn't support external HTTP requests by default. I can understand why. However, I found that couchjs can do HTTP requests

```
-H          enable couchjs cURL bindings (only avaiable
              if package was built with cURL available)
```

Apparently, -H works somehow, but there is no documentation about it. I was performing trial and error exploration and now I can use the CouchHTTP to perform external requests.

Is this undocumented part of the couchjs subject of change in the future? Can I use -H options without worrying that the option will be removed in a future version?

**Comment by wohali** [comment]
No, this feature is only used for our JavaScript test suite, which is being converted at the moment to Elixir.

Once that test suite is converted, this feature will be removed.

Using CouchHTTP to perform external requests from within the CouchDB runtime is considered a violation of the view server contract.

**Comment by ondra-novak** [comment]
Thank you for closing this very fast without going deeper into the question. I wanted to use this feature to run external process for conflict resolution or do  some other related tasks on servers (like a os_daemon, or started as service) - a maintenance for a couchdb database. Definitely not for views. The idea was to use simple JS engine which is already included into couchdb product. With http bindings, I can easily read/modify documents and listen for _changes. So question was, whether the option -H will be removed in future versions. It would be a pity, because the maintenance is part of database (at least to resolve conflicts) and couchdb offers weak or no support for such process. 

Yes, I can install node.js.

Or i can replace couchjs by node.js (?)

So with node.js, is couchjs useful any more?

Thank you, have nice day.

**Comment by wohali** [comment]
Leave your sarcasm out of the ticket please.

We have no intent to support any use for `couchjs` outside of its current uses by CouchDB itself. It was never intended to be used as a standalone JS interpreter for anything.

The answer to your question is: if  `couchjs` is replaced by an in-process JS daemon, then yes, that flag will vanish because there will be no external process anymore.

The answer is also: once the JavaScript views are gone, the `-H` flag will also be removed, because it removes our build-time dependency on `libcurl`.
