### ISSUE TITLE
Cluster created using seedlist does not create system tables

### ISSUE THREAD

**Issue by matticala** [apache/couchdb#1900]
Related to:  #1658
CouchDB version: 2.3.0

What happens:
I am creating a cluster in Kubernetes using `seedlist` from environment variables. My cluster goes up, admin and secret are injected correctly but system tables are not created.

`_membership` correctly endpoint returns:
```
{
  "all_nodes": [
    "couchdb@couchdb-0.couchdb.couchdb.svc.cluster.local",
    "couchdb@couchdb-1.couchdb.couchdb.svc.cluster.local",
    "couchdb@couchdb-2.couchdb.couchdb.svc.cluster.local"
  ],
  "cluster_nodes": [
    "couchdb@couchdb-0.couchdb.couchdb.svc.cluster.local",
    "couchdb@couchdb-1.couchdb.couchdb.svc.cluster.local",
    "couchdb@couchdb-2.couchdb.couchdb.svc.cluster.local",
    "couchdb@couchdb-3.couchdb.couchdb.svc.cluster.local"
  ]
}
```
(the additional `couchdb-3` node is due to autoscaling)

but `_nodes`, `_metadata` and `_replicator` are missing.
From Fauxton I can still choose if want to setup a single node or a cluster.

Expected behaviour:
When providing a `seedlist`, a fresh couchdb cluster should go up creating and replicating system tables

I see the incubator helm chart from @kocolosk hasn't been updated for almost year. Is CouchDB able to go up without the helm of a sidekick?

**Comment by kocolosk** [comment]
Hi @matticala the Helm chart is seeing plenty of regular updates directly upstream:

https://github.com/helm/charts/commits/master/incubator/couchdb

Looking back at the original feature in #1658, I configured things so that the node-local databases would get replicated. That's `_nodes`, `_dbs`, and `_users` by default. So if you're not seeing `_nodes` on the new node, *and* the status in the `_up` endpoint claims seeding is complete, that's a bug.

Databases like `_metadata` and `_replicator` are a different story. I didn't do anything with them in the seedlist feature, so they would still need to be created. I can imagine that we could figure out a way to automate that as part of the original StatefulSet deployment in Helm, but I haven't done it. I don't think we're at a place where we would do any rebalancing of those databases on cluster scaling events yet.

I imagine this seedlist feature could be better integrated with the Fauxton cluster setup. I don't regularly use that feature and so it just wasn't top of mind for me. We could do better there, e.g. at least recognizing that a seedlist exists, checking the status, and then jumping to the appropriate phase of the setup.

**Comment by matticala** [comment]
Hi @kocolosk,

I can't see `_nodes` even in the seed node, the first one going up. Basically the whole cluster, freshly created, has no database. It's completely empty and Fauxton show the possibility to Setup Cluster or Single Node.
Querying the `_membership` endpoint though returns the node list.
When manually doing the Setup Cluster only `_global_changes` is created, if I remember correctly.

I was thinking to use `lifecycle` handlers for `postStart` (to `PUT` nodes) and `preStop` (to remove the terminated node), injecting them from a ConfigMap, instead of the sidecar. Have you tried it?

**Comment by kocolosk** [comment]
Note that `_nodes` is a local database, it won't show up in the clustered endpoint. Did you check the node-local endpoint on port 5986? Each node automatically creates this database on its own; the seedlist feature just ensures they all agree on the content 😄 

I haven't tried the `postStart` handler for this purpose but that is what I had in mind 👍

**Comment by matticala** [comment]
@kocolosk true, I haven't tried on 5986. I tried per-node but on 5984.

Thanks!
