### ISSUE TITLE
CouchDB Indexes Failing (Invalid Index Def ... Error: error, Reason: {badmatch,undefined})

### ISSUE THREAD

**Issue by Austint30** [apache/couchdb#1984]
CouchDB indexes failing due to undefined badmatch error

## Description

One of our databases has over 120k documents in it. Whenever our customers start using our system, CouchDB starts to have issues with failing view and mango query requests. The requests to views and mango queries take too long and end up with a Gateway timeout after 1 minute.

These issues are occurring on our central CouchDB server that runs version 2.1.1. We also have several local consoles running local CouchDB servers that run version 2.2.0. These local CouchDB instances replicate with our central CouchDB server. Could this version difference be a problem?

Looking at the couchdb.log file, I can see that there are many errors related to indexes:
```
[error] 2019-03-19T13:54:53.950019Z couchdb@127.0.0.1 <0.20603.598> -------- Invalid Index Def [{<<"map">>,{[{<<"fields">>,{[{<<"foo">>,<<"asc">>}]}},{<<"partial_filter_selector">>,{[]}}]}},{<<"reduce">>,<<"_count">>}]. Error: error, Reason: {badmatch,undefined}
```
This is only one of the many index errors. All of them have a {badmatch,undefined} reason. 

## Steps to Reproduce

Not sure how to reproduce this. But, our main database has over 120k documents. This database stores many different types of documents (type is defined by a classType field). Documents are also marked as deleted by including a deletedTs field. And we have about more than 20 indexes and many more views. The database is under pretty heavy usage during peak hours.

## Expected Behaviour

We have been expecting it to work like it did when the database was under 120k documents. Mango queries and requests to views should be returning results fairly quickly.

## Your Environment
Ubuntu 16.04
{"couchdb":"Welcome","version":"2.1.1","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

* CouchDB Version used: 2.1.1
* Browser name and version: Any Browser
* Operating System and version: Ubuntu 16.04

**Comment by wohali** [comment]
Hi there @Austint30 ,

I can promise you that CouchDB works fine with >120k documents frequently. It sounds like your hardware is underpowered and you need more CPU or need to bump the timeout, but that error you're seeing on your index is that Mango does not yet support reduces. Remove the `reduce` key.

You should also upgrade as soon as possible because of known security holes in both 2.1.1 and 2.3.0 as documented [here](http://docs.couchdb.org/en/stable/cve/index.html).

Unfortunately, This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by Austint30** [comment]
Hi @wohali 
The reduce key was added automatically when creating indexes using db/_index (or in the Fauxton interface under Mango Query).

**Comment by garrensmith** [comment]
Which version of Fauxton are you using?


________________________________

**Comment by Austint30** [comment]
I am using the version of Fauxton that came with CouchDB 2.1.1.
