### ISSUE TITLE
Unable to query /database/_all_docs as non server-admin

### ISSUE THREAD

**Issue by magnadoodle** [apache/couchdb#1986]
## Description

A `GET /<database>/_all_docs` request fails with `{"error":"unauthorized","reason":"You are not a server admin."}`, if you are not a server admin. 

My expectation is that if a normal user is a database admin of a particular database he or she should be able to query `_all_docs`. 

## Steps to Reproduce

1. Create a normal user
```
curl -X PUT http://localhost:5984/_users/org.couchdb.user:testuser \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"name": "testuser", "password": "test1234", "roles": [], "type": "user"}'
```

2. Make user to DB admin on e.g. _replicator Database
```
curl -X PUT http://localhost:5984/_replicator/_security \
     -u admin:password \
     -H "Content-Type: application/json" \
     -d '{"admins": { "names": ["testuser"], "roles": [] }, "members": { "names": [], "roles": [] } }'
```

3. Verify that testuser is an admin on _replicator db
```
curl http://localhost:5984/_replicator/_security
{"admins":{"names":["testuser"],"roles":[]},"members":{"names":[],"roles":[]}}
```

4. Try to query `/database/_all_docs` as non server admin and fail
```
curl http://testuser:test1234@localhost:5984/_replicator/_all_docs
{"error":"unauthorized","reason":"You are not a server admin."}
```

5. Try the same as server admin
```
curl http://admin:admin@localhost:5984/_replicator/_all_docs
{"total_rows":1,"offset":0,"rows":[
{"id":"_design/_replicator","key":"_design/_replicator","value":{"rev":"1-85a961d0d9b235b7b4f07baed1a38fda"}}
```

## Expected Behaviour

According to the documentation a database admin should be able to query '_all_documents' of a database.  

## Your Environment

* CouchDB Version used: 2.3.0; 2.3.1
* Operating System and version: Reproducable at least on CentOS 7.6 and with the official Docker Container

**Comment by wohali** [comment]
The `_replicator` DB is special - you shouldn't see this behaviour on other DBs.

@nickva can respond to this.

**Comment by nickva** [comment]
@magnadoodle, @wohali is right, `_replicator` is special. 

The idea was that `_replicator` in CouchDB 1.x could only be a single database per server. So in the case with multiple users, one of them could list the replicator doc for all the other users and view their credentials.

However there is another feature in 2.x that lets you bypass this in a way. It turns out, in CouchDB 2.x you can have multiple replicator dbs! Basically any database that ends with the `/_replicator` will be a `_replicator`. For example `other/_replicator` or `my/_replicator`, etc. And it turns out those additional replicator dbs don't have this restriction that only server admin can perform `_all_docs`!

Let's try it out:

```
$ curl -XPUT http://adm:pass@localhost:15984/other%2f_replicator
{"ok":true}
```
[!] Notice: I urlencoded `/` as `%2f` so it is not interpreted as db=`other` and doc=`_replicator`

Then I followed the same steps as you to add the test user. And then add the new user to `_replicator` and `other/_replicator` as admins.

```
$ curl http://adm:pass@localhost:15984/_replicator/_security
{"admins":{"names":["testuser"],"roles":[]},"members":{"names":[],"roles":[]}}

$ curl http://adm:pass@localhost:15984/other%2f_replicator/_security
{"admins":{"names":["testuser"],"roles":[]},"members":{"names":[],"roles":[]}}
```

Now notice that I can't query `_all_docs` on `_replicator` but can on `other/_replicator`.

```
$ curl http://testuser:test1234@localhost:15984/_replicator/_all_docs
{"error":"unauthorized","reason":"You are not a server admin."}


$ curl http://testuser:test1234@localhost:15984/other%2f_replicator/_all_docs
{"total_rows":1,"offset":0,"rows":[
{"id":"_design/_replicator","key":"_design/_replicator","value":{"rev":"1-85a961d0d9b235b7b4f07baed1a38fda"}}
]}
```




Now when using / in the URL you'd have to escape it.`

**Comment by magnadoodle** [comment]
@whoali @nichva Thanks for the detailed answer. I understand these design considerations. But this makes it really hard to monitor CouchDB 2 in a secure way. I will try if @nickva's approach to use another Database as _replicator DB is viable for me.

What do you think about API Endpoints to expose information about running Replications (without DB credentials) and DB Stats, which are also only accessible to DB Admins since Version 2 to read-only users? If you like the idea I will file a feature request.

**Comment by nickva** [comment]
@magnadoodle _active_tasks, _scheduler/jobs and _scheduler/docs should probably be used to monitor replications. If you specifically look at document states, then _scheduler/docs is probably the first to try

https://docs.couchdb.org/en/stable/api/server/common.html#get--_scheduler-docs-replicator_db

**Comment by magnadoodle** [comment]
@nickva thanks I will take a look at that! So I will close this one.
