### ISSUE TITLE
CouchDB 2.0: Race condition when creating/deleting database

### ISSUE THREAD

**Issue by niconorsk** [apache/couchdb#2073]
Reposting of https://issues.apache.org/jira/browse/COUCHDB-3034 as this is still an issue

## Description

I've noticed that CouchDB 2.0 (master) occasionally returns 500 errors when multiple clients attempt to PUT or DELETE the same database concurrently. 

## Steps to Reproduce

This is reproducible by running multiple instances of following script in parallel against an n=1 (single node) cluster:
```
#!/bin/bash

for i in `seq 1 2000`;
do
	printf '\nPUT: '
    curl -XPUT 'http://localhost:15984/testdb' -w "%{http_code}\\n"
    printf '\nDELETE: '
    curl -XDELETE 'http://localhost:15984/testdb' -w "%{http_code}\\n"
done
```
This generates output along the lines of:
```
PUT: {"ok":true}
201

DELETE: {"ok":true}
200

PUT: {"error":"error","reason":"internal_server_error"}
500

DELETE: {"error":"not_found","reason":"Database does not exist."}
404

PUT: {"error":"file_exists","reason":"The database could not be created, the file already exists."}
412

DELETE: {"ok":true}
200

PUT: {"error":"file_exists","reason":"The database could not be created, the file already exists."}
412

DELETE: {"ok":true}
200

PUT: {"ok":true}
201

DELETE: {"ok":true}
200
```
## Your Environment

* CouchDB Version used: 2.3.1 installed from RPM
* Browser name and version: curl
* Operating System and version: CentOS 7.5

**Comment by janl** [comment]
this is really expected behaviour in a clustered database. 4.0 is likely going to address this, but until then, you’ll have to work around this with unique db names per iteration (plus cleanup) or sleep timeouts.

**Comment by romanofski** [comment]
@janl Thank you for your response. Would you mind pointing to documentation (issues, design documents, whatever) or elaborating why this is expected behaviour in a clustered database? I'm asking, because I don't have much experience with clustered databases and would like to understand the underlying problem better. The other reason why I'm asking is: you say that it will be addressed in upcoming releases. Does that mean that is perhaps not as expected? It sounds like there are cases where this behaviour is unexpected and those should be addressed? Which are they?

Thanks again if you'd be so kind to explain.
