### ISSUE TITLE
Filtered _bulk_docs

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb#2093]
Improvements to easly implement UPDATE WHERE feature above CouchDB

## Summary

Extend the update function request to handle an update of multiple documents

## Desired Behaviour

```
POST /{db}/_design/{ddoc}/_update/_bulk_docs?filter=doc/flt&args....
POST /{db}/_design/{ddoc}/_update/_bulk_docs?view=doc/view&args....
POST /{db}/_design/{ddoc}/_update/_bulk_docs?view=doc/view&start_key=xxx&end_key=yyy&args....
POST /{db}/_design/{ddoc}/_update/_bulk_docs?view=_all_docs&start_key=xxx&end_key=yyy&args....
```

The function should pick documents selected by a filter or by a view. For view it can use index to make operation faster. Selected documents are send to update function one by one. Output of the update function is ignored. Result is report about how documents has been updated (new revisions, etc)

## Additional context

I often need to perform a mass update which currently is possible by combination of mass get, update and mass put which involves massive data transfers from and into database

**Comment by wohali** [comment]
Editing title to make the request clearer

**Comment by ondra-novak** [comment]
Forget it. i am no longer support CouchDB.

**Comment by wohali** [comment]
Your title "bulk update" isn't specific enough. Feel free to make it even more specific.

**Comment by rnewson** [comment]
Regardless of the title (which could have been clarified amicably if all participants had remained civil), we are deprecating the `_update` endpoint for removal in a future release, and would not accept your forthcoming Pull Request to extend its functionality. The idea itself is sound otherwise, but it's not the direction we are taking CouchDB.

**Comment by janl** [comment]
PMC Chair here, with a formal CoC violation notice.

After this issue played out, OP went on twitter to insult, misgender, and misrepresent Joan’s affiliation.

This is a CoC violation on multiple levels:
1.

<details>
https://mobile.twitter.com/novacisko/status/1157358919158763520
![IMG_9836](https://user-images.githubusercontent.com/11321/62422795-55216380-b6b8-11e9-9af0-7e091a24877a.PNG)
![IMG_9835](https://user-images.githubusercontent.com/11321/62422797-55216380-b6b8-11e9-9eb8-b5c56cfddf1f.PNG)
![IMG_9834](https://user-images.githubusercontent.com/11321/62422798-55216380-b6b8-11e9-9e4b-cd4ab098ee1f.PNG)

</details>

**Comment by janl** [comment]
PMC Chair here, with a formal [CoC](http://couchdb.apache.org/conduct.html) violation notice.

After this issue played out, OP went on twitter to insult, misgender, and misrepresent Joan’s affiliation.

This is a CoC violation on multiple levels:

1. the personal insult, of whatever nature, is not behaviour we tolerate in the project. It doesn’t matter if this happens on our GitHub, Mailing Lists or anyone’s public Twitter. This is a clear and intentional transgression.

2. the insult in particular is ableist, and as per our diversity statement, we are pointing out that this is language we don’t tolerate at the project.

3. Joan’s been misgendered as a “he” is a clear sign of disrespect, again, not tolerated.

4. OP in their tweets imply that Joan is “employed by CouchDB”. The CouchDB project does not employ anyone. While this does not constitute a CoC violation, I’m taking this space to set the record straight.

As an immediate result of this, I’m locking this issue and blocking OP from this organisation for the foreseeable future.

For any questions, please contact private@couchdb.apache.org.

<details>
https://mobile.twitter.com/novacisko/status/1157358919158763520
![IMG_9836](https://user-images.githubusercontent.com/11321/62422795-55216380-b6b8-11e9-9af0-7e091a24877a.PNG)
![IMG_9835](https://user-images.githubusercontent.com/11321/62422797-55216380-b6b8-11e9-9eb8-b5c56cfddf1f.PNG)
![IMG_9834](https://user-images.githubusercontent.com/11321/62422798-55216380-b6b8-11e9-9e4b-cd4ab098ee1f.PNG)
</details>
