### ISSUE TITLE
Conflict when adding a previously deleted document

### ISSUE THREAD

**Issue by manufont** [apache/couchdb#2139]
I'm getting a "Document update conflict" when adding a previously deleted document.
## Description
```
$ curl http://localhost:5984/mydb/mydocument
{"error":"not_found","reason":"deleted"}
$ curl http://localhost:5984/mydb/mydocument -X PUT --data-binary '{}'
{"error":"conflict","reason":"Document update conflict."}
```
## Expected Behaviour
```
$ curl http://localhost:5984/mydb/mydocument
{"error":"not_found","reason":"deleted"}
$ curl http://localhost:5984/mydb/mydocument -X PUT --data-binary '{}'
{"ok":true,"id":"mydocument","rev":"723-..."}
```
​
The reason I'm creating this issue is that I can't find a single case where this situation could occur. I've searched the documentation, stackoverflow & github and couldn't find a similar case. If the winning revision is a deleted leaf, then why is there a conflict when I try to add a new document with same ID ?
I suspect a _purge of the 3 last revisions of this document might be the origin of this problem, but I couldn't reproduce it with other documents.
​
Is there a way to manually resolve conflicts for deleted documents ? I've tried the flags `conflicts=true` & `deleted_conflicts=true` flag, but it didn't work.

​
The only way I could find to resolve this conflict was the following:
​
1. get the last revision id
```
$ curl http://localhost:5984/mydb/_changes?filter=_doc_ids&doc_ids=["mydocument"]
{"results":[{"seq":"234234-...","id":"mydocument","changes":[{"rev":"722-46b..."}],"deleted":true}],"last_seq":"123123-...","pending":345345}
```
2. update the deleted document
```
$ curl http://localhost:5984/mydb/mydocument -X PUT --data-binary '{"_id": "mydocument", "_rev":"722-46b...", "_deleted": true}'
{"ok":true,"id":"mydocument","rev":"723-..."}
```
3. adding it again
```
$ curl http://localhost:5984/mydb/mydocument -X PUT --data-binary '{}'
{"ok":true,"id":"mydocument","rev":"724-..."}
```

Another odd behaviour caught my attention: I can get 2 other revisions hash for this document:
```
$ curl http://localhost:5984/mydb/mydocument?rev=722-46b...&revs=true
{"_id":"mydocument","_rev":"722-46b...","_deleted":true,"_revisions":{"start":722,"ids":["46b...","63b..","3de..."]}}
```
But when I try getting them (with every possible revision index), I only get "missing" errors...
​
## Your Environment
{"couchdb":"Welcome","version":"2.3.1","git_sha":"c29...","uuid":"fc3...","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
There's one "server" couch, configured with a 2-way replication to a dozen of Pouchdb "clients".
To limit conflicts, the documents are updated server-side only.
The _revs_limit value of all databases is set to 3, as we've got storage constraints on pouchdb clients.

**Comment by manufont** [comment]
I did a one-time replication of this database, and the issue disappeared on the target: The document was created without any problem. This issue is still present on the source though.

**Comment by wohali** [comment]
@manufont Yup, that's expected in the target, since the document "tombstone" won't appear in the target.

As for your primary case, reducing _revs_limit creates replication issues. If a common ancestor of an update cannot be found, then a new branch is created - in other words, a conflict is created.

We don't recommend changing _revs_limit at all, so we're going to have to close this as outside of our recommended usage guidelines. Sorry about that.

See #1994 for a similar situation.

**Comment by xrobau** [comment]
I'm REALLY REALLY sorry to necro-comment on this ticket, but it's the first google result for this problem, and is annoyingly tricky to solve once you get yourself into this state.  We have a 5 node cluster, and one record was 100% broken because of this. It was returning 404 deleted, but could not be updated (and note we have NOT changed _revs_limit from the default, whatever it may be)

If anyone ELSE is having this problem, and the instructions above don't fix it, you will have to purge the record before you can recreate it.  Here's what my journey was:

```
DBURL='http://admin:admin@10.10.10.10:5984/sad_db'
RECORD=Broken.3924858000126984351
curl "$DBURL/_changes?filter=_doc_ids&doc_ids=\[\"$RECORD\"\]"
```
That gave me the rev of when it was deleted, which was `2-9c504538e77f1ef3eff158b0f99a6c63` in this case

```
R=2-9c504538e77f1ef3eff158b0f99a6c63
curl "$DBURL/$RECORD?rev=$R"
```

I tried posting that straight back, so it would just bump the revision but not change any data, but still had the document conflict. I also tried setting random keys/values/etc to try to make it create rev3, but it wouldn't work and was completely stuck.

This appears to be some sort of edge case bug that I didn't have time to diagnose, so I had to just use the shotgun method, and purge the record and hope that this doesn't cause issues with other nodes that were replicating from this one!

```
curl -X POST "$DBURL/_purge" -d "{\"$RECORD\":\[\"$R\"\]}" -Hcontent-type:application/json
```

I was then able to import it again, and it appeared as a new record with rev 1.
