### ISSUE TITLE
Stale views in clustered db

### ISSUE THREAD

**Issue by man4j** [apache/couchdb#2294]
If i save/update document to node A and then I request document from node B by view - not always I get back latest version. But if I request directly by REST API - all work's ok. I think when I get a response from node A,  views on other nodes not synchronously updated.

* CouchDB Version used: 2.3.1
* Operating System and version: CentOS 7

**Comment by davisp** [comment]
You mention the REST API as different from what you're using to make requests which has me confused.

If you want to ensure that a view response includes a write the easiest method is to add the `?w=3` request parameter so that you know it exists on all nodes before attempting the view read. A view response starts once all shard ranges have returned a response which means if a third copy has yet to fsync a document write its more likely to be the fastest response and included as part of the view output.
