### ISSUE TITLE
Downloadable HTML Documentation is empty of content

### ISSUE THREAD

**Issue by pablobm** [apache/couchdb#2384]
The link to download an HTML version of the documentation only contains the index, images and fonts.

## Description

I want to download the documentation in HTML format for offline use. The offered download doesn't actually contain the documentation.

## Steps to Reproduce

1. At the documentation site, follow the link "Download docs". This is near the bottom of the sidebar, under "More Help", and it links to https://docs.couchdb.org/en/stable/download.html
2. Three downloads are offered: PDF, HTML and EPUB. Click HTML. This will start a download of a zip file.
3. The zip file contains several files, including images, JS and the index of the documentation. However it doesn't include the documentation itself. The links from the index do not work.

## Expected Behaviour

I would expect:

1. The links from the downloaded index to lead somewhere.
2. The CouchDB documentation to be included in the zip file.

**Comment by wohali** [comment]
Hi @pablobm ,

This is unfortunately a problem with readthedocs.org, who host our documentation for us:

* https://github.com/readthedocs/readthedocs.org/issues/3242
* https://github.com/readthedocs/readthedocs.org/issues/4190

Worse, because of our build approach, the single `index.html` file only includes the splash page, not the full contents.

Because this page is generated by the RTD service and their template, we have no control over its format or contents.

Fortunately, there's a workaround. Just download the prebuilt CouchDB **tarball** from https://couchdb.apache.org/ that matches your version of CouchDB, unpack it, and open `share/docs/html/index.html` with your favourite browser.
