### ISSUE TITLE
Output the _rev by default in views (similar to _id)

### ISSUE THREAD

**Issue by elChapoSing** [apache/couchdb#2387]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Output the _rev by default in views (similar to _id)

## Desired Behaviour

Whenever the `_id` shows in a view result, also show `_rev` (same hierarchical level).

## Possible Solution

My guess is when you output the `_id`, the `_rev` is also present so wouldn't take a lot of effort to include it in the result ?

## Additional context

At the moment when you query a view, you get the `_id` as a way to identify which record has gotten you which information. It would be very useful to also have the `_rev` in case one needs to make modification to the queried data.
It would prevent the user from having to query each individual `_rev` based on the `_id`, or build a new exactly similar index to get the `_rev` or use the `include_docs=true` flag, hence saving calculation time and/or data transfer.

**Comment by janl** [comment]
I think this is a useful addition IF we can make it efficient to provide.

Currently, CouchDB internally needs to store the doc `_id` inside a view index to effectively perform view updates. Because it is already in the index, we show it with every result*. If the view index already also includes the `_rev` for each row (something I’m not sure about at the moment), then we could add an option along the lines of `?include_rev=true` to show it as well.

If the `_rev` is NOT already in the view index, would not suggest we add, just for this feature for performance reasons.

* there might be a valid reverse request to hide the id if it is not needed (`?include_id=false` maybe)

**Comment by janl** [comment]
Is someone here up for checking if the `_rev` is already part of a view index?

**Comment by elChapoSing** [comment]
Beyond my skillset I'm afraid.

**Comment by kocolosk** [comment]
To the best of my knowledge it is not.

**Comment by elChapoSing** [comment]
How does couch know which _rev of each _id to use in views ?

**Comment by janl** [comment]
@elChapoSing by reading the _changes feed, which has that info. My memory agrees with @kocolosk, so I’m closing this. Sorry about this! :)
