### ISSUE TITLE
Missing new document right after 'No DB shards could be opened' error

### ISSUE THREAD

**Issue by uvizhe** [apache/couchdb#2880]
## Description
I've posted a new doc to my DB but it's missing somehow. POST request returned Ok.
Looking at logs I see an error message right before my POST.

## Steps to Reproduce
IDK
## Expected Behaviour
I would either expect to see a posted document in a DB or a failed POST request.
## Your Environment
I'm running CouchDB in a Docker container on a local PC.
My CouchDB has 3 databases with less than a hundred docs overall.
* CouchDB version used: v. 3.0.0 (https://github.com/apache/couchdb-docker)
* Operating system and version: Ubuntu 16.04.4 LTS

## Additional Context
As per config:
```
[couchdb]
max_dbs_open = 500
[cluster]
q=2
n=3
```
Here is two consecutive log messages:
```
[error] 2020-05-09T07:37:05.795627Z nonode@nohost <0.26146.358> 57464f6b16 req_err(3763885668) internal_server_error : No DB shards could be opened.
    [<<"fabric_util:get_shard/4 L111">>,<<"fabric_util:get_shard/4 L128">>,<<"fabric_util:get_shard/4 L128">>,<<"fabric:get_security/2 L183">>,<<"chttpd_auth_request:db_authorization_check/1 L110">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:handle_req_after_auth/2 L320">>,<<"chttpd:process_request/1 L305">>]
[notice] 2020-05-09T07:37:05.796734Z nonode@nohost <0.26146.358> 57464f6b16 couchdb:5984 172.17.0.5 dbuser POST /database 500 ok 307
```

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only. We're quite sure the Docker container works due to exhaustive testing. Most likely, you have misconfigured the node name vs. the data stored for the databases you're trying to access. Your POST request returned 500, not 200, so it very much was not an OK.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
