### ISSUE TITLE
setting "syslog_facility" is ignored

### ISSUE THREAD

**Issue by rg54** [apache/couchdb#3882]
## Description

With this configuration for logging : 
> [log]
> level = info
> writer = syslog
> syslog_appid = couchdb
> syslog_facility = local2

Syslog logging is working, but target facility is "daemon" (ID=3), and not "local2" (ID=18)

As this journalctl JSON export is showing it : 

> {
>         "__CURSOR" : "s=xxxxxxxxxx;i=1ae8ea;b=xxxxxxxxx;m=xxxxx;t=xxxxxxxxx;x=xxxxxxxxxxxxxxxx",
>         "__REALTIME_TIMESTAMP" : "1640190335842907",
>         "__MONOTONIC_TIMESTAMP" : "97577941459",
>         "_BOOT_ID" : "xxxxxxxxxxxxxxxx",
>         "PRIORITY" : "6",
>         "_SELINUX_CONTEXT" : "unconfined\n",
>         "_SYSTEMD_SLICE" : "system.slice",
>         "_MACHINE_ID" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>         "_HOSTNAME" : "Vm-xxxxxx-couchdb0",
>         "_TRANSPORT" : "stdout",
>         **"SYSLOG_FACILITY" : "3",**
>         "_CAP_EFFECTIVE" : "0",
>         "SYSLOG_IDENTIFIER" : "couchdb",
>         "_UID" : "111",
>         "_GID" : "116",
>         "_COMM" : "beam.smp",
>         "_EXE" : "/opt/couchdb/erts-9.3.3.15/bin/beam.smp",
>         "_CMDLINE" : "/opt/couchdb/bin/../erts-9.3.3.15/bin/beam.smp -K true -A 16 -Bd -Q 500000 -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /opt
>         "_SYSTEMD_CGROUP" : "/system.slice/couchdb.service",
>         "_SYSTEMD_UNIT" : "couchdb.service",
>         "_STREAM_ID" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>         "_PID" : "30134",
>         "_SYSTEMD_INVOCATION_ID" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>         "MESSAGE" : "<149>1 2021-12-22T16:25:35.842004Z xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> }

## Steps to Reproduce

- install CouchDB 3.2.1 on Ubuntu, with distro packages
- use this syslog logging configuration
- check logs output (used command : `journalctl -t couchdb --since "1 minute ago" -o json-pretty` )

## Expected Behaviour

Logs should be sent to syslog with "local2" facility

## Your Environment

CouchDB 3.2.1 installation with distro packages, on Ubuntu 18.04.6 LTS

**Comment by nickva** [comment]
@rg54 The log line you have is from journalctl so it looks like it was forwarded there somehow. I verified on a system which runs just rsyslog that we are sending logs to `local2` facility. I can see the messages have the appropriate `<Priority>` prefix.  (`Priority` for syslog is `Facility * 8 + Level`).

In your case perhaps it helps to see how log forwarding happens to the journal, at some point the message priorities may be overridden to have the general "daemon" facility since they end up in journald...

**Comment by nickva** [comment]
CouchDB's syslog only knows how to use UDP logging. In order to make it work need two changes:

 * Enable UDP socket rsyslog module
```
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")
local2.*			-/var/log/local2.log
```
 * Make sure to specify a host for the CouchDB's log syslog parameter (localhost should work)
```
[log]
level = info
writer = syslog
syslog_host = localhost
syslog_appid = couchdb
syslog_facility = local2
```

Then both CouchDB and logger should work. For logger make sure to explicitly force it to use UDP logging otherwise it will still log also to the journal.

```
$ logger  -P 514 -p local2.info -n 127.0.0.1 -d "Test1"
```

**Comment by big-r81** [comment]
Okay, will try it out. But this info about UDP needs to go into the docs, because it’s not obvious for the syslog writer…

**Comment by nickva** [comment]
@big-r81 good call about the documentation gap. Definitely needs updated.
