### ISSUE TITLE
See if it is possible to optimize a couch_util:reorder_results/2

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#4051]
Looking at https://github.com/apache/couchdb/blob/369ecc98115f60ee6cabb4dac246dcb6817c56a6/src/couch/src/couch_util.erl#L526-L531

With the recent map optimization in couch_key_tree on OTP 23, it be might worth double-checking if we can get some performance improvements by having a different cutoff value for linear search instead of 100, or use a map instead of a dict.

A quick informal benchmark showed a nice improvement when using a map reordering 1000 16 byte random doc IDs and values (Results are in iterations per second):
```
> f(Gen), Gen = fun(N) ->
    Keys = [crypto:strong_rand_bytes(16) || _ <- lists:seq(1, N)], 
    Res = lists:sort([{K, crypto:strong_rand_bytes(16)} || K <- Keys]), 
   {Keys, Res}
end.
```

```
> f(Keys), f(Res), {Keys, Res} = Gen(1000), ok.
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, map]}}).
5434
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, dict]}}).
1219
```

500 DocIDs
```
> f(Keys), f(Res), {Keys, Res} = Gen(500), ok.
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, dict]}}).
2407
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, map]}}).
11639
```

200 DocIDs
```
> f(Keys), f(Res), {Keys, Res} = Gen(200), ok.
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, map]}}).
36267
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, dict]}}).
6870
```

Stays pretty consistent around 5x.

The function is called from `fabric_doc_update` and `couch_btree:lookup/2` which is in the hotpath of a good number of API calls (I mainly started looking at it with the eye to optimize _revs_diff implementation to speed-up replication a bit).

**Comment by nickva** [comment]
The quick and dirty patch:

```diff 
diff --git a/src/couch/src/couch_util.erl b/src/couch/src/couch_util.erl
--- a/src/couch/src/couch_util.erl
+++ b/src/couch/src/couch_util.erl
@@ -530,6 +531,17 @@ reorder_results(Keys, SortedResults) ->

+% linear search is faster for small lists, length() is 0.5 ms for 100k list
+reorder_results2(Keys, SortedResults, Cutoff, _DictType) when length(Keys) < Cutoff ->
+    [couch_util:get_value(Key, SortedResults) || Key <- Keys];
+reorder_results2(Keys, SortedResults, _Cutoff, map) ->
+    Map = maps:from_list(SortedResults),
+    [maps:get(Key, Map, undefined) || Key <- Keys];
+reorder_results2(Keys, SortedResults, _Cutoff, dict) ->
+    KeyDict = dict:from_list(SortedResults),
+    [dict:fetch(Key, KeyDict) || Key <- Keys].
+
```

**Comment by iilyak** [comment]
Another possible optimization. 

If the function is always called in the context when passed results are sorted (and sorting method is compatible with erlang sorting) then we can use `orddict:fetch/2` instead of `couch_util:get_value/2`.

In case of `couch_btree:lookup/2 ` the sorting is guaranteed see [couch_btree.erl#L272:L275](https://github.com/apache/couchdb/blob/0059b8f90e58e10b199a4b768a06a762d12a30d3/src/couch/src/couch_btree.erl#L272:L275). 

In case of `fabric_doc_update` it might be not the case (quick review is not conclusive). Which means our variable name `SortedResults` is misleading.  

I wish erlang had `length_greater_than/2`. The `length/1` in the first clause still concerns me. However it seems like there is no option to remove it. Also IRC the keys are passed via API. It is unlikely we can get above 100k of elements.

**Comment by nickva** [comment]
Optimization PR merged. Closing issue.
