### ISSUE TITLE
v3.3.1 compaction smoosh config

### ISSUE THREAD

**Issue by tophe** [apache/couchdb#4378]
## Description
upgrading to couchdb 3.3.1 from 3.2.1, I have an issue with compaction who start but should not in 3.3.1 (wasn't starting in 3.2)
local.ini:
[smoosh]
db_channels = ratio_dbs
view_channels = ratio_views

[smoosh.ratio_dbs]
priority = ratio
min_priority = 2.0
from = 00:00
to = 06:00
strict_window = true
concurrency = 1
# max size 5Go !
max_size = 5000000000

that config was honored by couchdb 3.2.1, I haven't compaction for shard > 5Gb, when couchdb 3.3.1 start with the same configuration it start to compact data files > 5Gb, not honouring window time.

## Steps to Reproduce

use local.ini config with a max_size of 1000 (small shard dbs), make a db file of more than 1k file, with delete big ratio.
observe if compaction start.

## Expected Behaviour

don't compact file shard > 5Gb

## Your Environment
docker official image.

* CouchDB version used:
* 3.3.1
* Browser name and version:
firefox
* Operating system and version:
debian bulleyes

## Additional Context

the smoosh setup work with 3.2.1, databases was never compacted, I use this setup because the database is essentialy an image repository from more than 20Tb, if compaction start, it take all the io and the db become unresponsive.
When I updrad the container to 3.3.1, it compact databases when it start, that wasn't the 3.2 behavior.

**Comment by nickva** [comment]
@tophe the reason is likely because of how the default channels were disabled by removing them from the config. As of 3.3 those channel are always present (to allow adding new default system channel to the list). If you don't want the them to be active, you may set their `concurrency` to 0 as a better way to disable them. But removing from the config list doesn't work a disabling mechanism any longer.

So you could try doing:

```
[smoosh.$channel]
concurrency = 0
...
```

Where `$channel` could be one of `upgrade_dbs, ratio_dbs,slack_dbs, upgrade_views, ratio_views, slack_views, index_cleanup` + other custom channels you may have.

Another reason, I which may affect you is the change in the size calculation. Previously the document bodies which would have been deleted during compaction would have counted for the active size calculation. That is no longer the case. See the commit https://github.com/apache/couchdb/pull/4264 for more details. You may have to adjust your ratio value if it was previously set too low accounting for how the active size was erroneously inflated.

**Comment by tophe** [comment]
so, I have disable the 
[smoosh.upgrade_dbs]
concurrency = 0
don't change anything.

then
[smoosh.ratio_dbs]
concurrency = 0
don't change anything

then
[smoosh.slack_dbs]
concurrency = 0

oh great the compaction stop on restart. So I guess the problem come from slack_dbs, but looking to the documentation.
I don't find anything about him.
I have updated all my configurations removing the slack_dbs channel, and everything run fine now.
Having some mention about that in documentation, could be a great help.

@nickva thank you for your help, issue closed.

**Comment by nickva** [comment]
Thank you for reaching out, @tophe. Good idea to add this info documentation, that's would have helped in this case.
