### ISSUE TITLE
Spidermonkey 91 is EOL and unsupported

### ISSUE THREAD

**Issue by RaitoBezarius** [apache/couchdb#4825]
CouchDB 3.x series currently only support Spidermonkey 91, this dependency has been EOL for a long time now.
In nixpkgs, we have a CouchDB packaging for the branch 3.x, we would like to package it using non-EOL SM.

Do you have a timeline or any plan to move away from SM91 in the future?

cc https://github.com/NixOS/nixpkgs/issues/157874

**Comment by nickva** [comment]
Thanks for the heads-up @RaitoBezarius. We're investigating using QuickJS https://github.com/apache/couchdb/issues/4448 but so far it hasn't made into a release yet. After the discussion in the Apache CouchDB meeting the plan is to release as an option first along with an automated background scanner to check users' design docs for compatibility between SM and QuickJS (or potentially any other JS engine in the future).

I had tried to bring SM 102 in with https://github.com/apache/couchdb/pull/4305 but they keep changing the C++ API almost every release so that didn't get very far.

Recent RHEL versions have removed spidermonkey from their base packages I see Debian Bookworm still supports https://packages.debian.org/bookworm/libmozjs-78-0. Presumably they have security patches for it as well? Perhaps nixpkgs can use the Debian version?

**Comment by big-r81** [comment]
@nickva Bookworm has v102 now too, but v102 has no security support too and v115 will end in one year [[1](https://endoflife.date/firefox)]. This matures fast ...

**Comment by nickva** [comment]
@big-r81 we can't use 102 they changed the C++ API

**Comment by big-r81** [comment]
I know and maybe v102 -> v115 again ...  ;-)

**Comment by nickva** [comment]
Exactly!

**Comment by githubowl** [comment]
Ok, I'll have to check thanks

**Comment by chenrui333** [comment]
any updates on the thread?

**Comment by xnox** [comment]
I see that quickjs is merged into main branch, is there a release coming soon? or at least an rc tag? it would be interesting to try out quickjs builds.

**Comment by nickva** [comment]
@xnox we're working toward a 3.4 release. QuickJS will be released as an experimental change, off by default,  with a scanner option to validate your views for compatibility. 

To try it out off of the `main` branch using QuickJS as a default:  `./configure --disable-spidermonkey` (add `--dev` if you don't want to build Fauxton or docs). Then `make && make release`

Some Linux OS still maintain SM 78 packages, so that may still be an option if you can use those.

**Comment by xnox** [comment]
@nickva i am linux distribution and was hoping to axe mozjs 91 from wolfi-os =)

**Comment by big-r81** [comment]
Closing this, SpiderMonkey support for versions >91 was added with 2cfb0c3764ee811b70213df4dcea1de5618187fe.
