### ISSUE TITLE
live change feed with limit never completes

### ISSUE THREAD

**Issue by ronag** [apache/couchdb#5200]
```curl http://127.0.0.1:5984/myDb/_changes?feed=continouos&limit=256``` will stay alive even after 256 changes have been read.

**Comment by nickva** [comment]
After 256 rows are emitted, because of the `feed=continuous` parameter, it will wait until the default timeout expires (60 seconds it seems). Yeah, that is a bit of odd behavior.  It seems if we emitted >= limit rows, we could end the request early, despite the timeout.

[Docs say](https://docs.couchdb.org/en/stable/api/database/changes.html#continuous):

> A continuous feed stays open and connected to the database until explicitly closed and changes are sent to the client as they happen, i.e. in near real-time.

but also

> If limit has been specified the feed will end with a { last_seq } object.

Continuous seems to take precedence regardless of limit

I guess in general it may be possible to control the time it will keep waiting with an explicit `timeout=$msec` parameter:
```
curl http://127.0.0.1:5984/myDb/_changes`?feed=continouos&limit=256&timeout=5000`

**Comment by rnewson** [comment]
that combination of parameters is unusual. "continuous=true" meaning "keep going" and "limit=X" meaning "stop after X".

A few options;

1) make the combination illegal (400 Bad Request)
2) Make the response end immediately after the X'th row is sent.

I think 2 is the right move
