### ISSUE TITLE
1.1.2. Installation from source

### ISSUE THREAD

**Issue by mikkimichaelis** [apache/couchdb#5313]
[1.1.2. Installation from source](https://docs.couchdb.org/en/stable/install/unix.html#installation-from-source)

produces the following on a fresh 22.04

``` bash
ubuntu@ip-172-31-34-232:~$ sudo apt-get --no-install-recommends -y install \
    build-essential pkg-config erlang \
    libicu-dev libmozjs185-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libmozjs185-dev
```

This is similar to [1316](https://github.com/apache/couchdb/issues/1316) which states libmozjs185 is now packaged.

**Comment by big-r81** [comment]
For running from source, you need one of the listed spidermonkey libs from the section above. 
In Ubuntu Jammy you could install `libmozjs-91-dev` or `libmozjs-91-dev` to get this working.

Since you are trying to build CouchDB from source, the section with the [dependencies](https://docs.couchdb.org/en/stable/install/unix.html#dependencies) gives you information, what you need to install. The `apt` command or later the `make` script will tell you, whats eventually missing.

**Comment by mikkimichaelis** [comment]
so basically I can't run from source on 22.04.

**Comment by big-r81** [comment]
> so basically I can't run from source on 22.04.

you can, you need to install the necessary packages ...
