### ISSUE TITLE
"Reduce output must shrink more rapidly" misrepresents which view is problematic

### ISSUE THREAD

**Issue by elistevens** [apache/couchdb#544]
When multiple views exist in the same design document, CouchDB 2.0 does not distinguish between the view being queried at the time and the view causing an error in the logged error messages.

## Expected Behavior

CouchDB should specify which view resulted in the error.

## Current Behavior
```
[info] 2017-05-25T19:15:38.649223Z couchdb@localhost <0.17653.11> -------- Starting index update for db: shards/a0000000-bfffffff/m3d_request.1495739240 idx: _design/mms.worker.request
[info] 2017-05-25T19:15:41.226488Z couchdb@localhost <0.16513.11> -------- OS Process #Port<0.18751> Log :: function raised exception (new TypeError("doc.state.fractionGroup_info is undefined", "undefined", 5)) with doc._id started_2013-04-29_12.07.28.801694_a5e86414c252c36ceb68b7aacedc9eda
[error] 2017-05-25T19:15:41.652864Z couchdb@localhost <0.23076.11> -------- OS Process Error <0.16513.11> :: {<<"reduce_overflow_error">>,<<"Reduce output must shrink more rapidly: Current output: '[{\"linacTpsRequest_cid\":\"linac_tps_2015-03-13_14.46.37.287005_185313df929b11bd40cbdee210cff04a\",\"lin'... (first 100 of 441 bytes)">>}
[error] 2017-05-25T19:15:41.653329Z couchdb@localhost emulator -------- Error in process <0.23076.11> on node couchdb@localhost with exit value:
{{nocatch,{<<"reduce_overflow_error">>,<<"Reduce output must shrink more rapidly: Current output: '[{\"linacTpsRequest_cid\":\"linac_tps_2015-03-13_14.46.37.287005_185313df929b11bd40cbdee210cff04a\",\"lin'... (first 100 of 441 bytes)">>}},[{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,59}]},{couch_query_servers,proc_prompt,2,[{file,"src/couch_query_servers.erl"},{line,427}]},{couch_query_servers,os_rereduce,3,[{file,"src/couch_query_servers.erl"},{line,135}]},{lists,zipwith,3,[{file,"lists.erl"},{line,450}]},{couch_query_servers,rereduce,3,[{file,"src/couch_query_servers.erl"},{line,93}]},{couch_mrview_util,'-make_reduce_fun/2-fun-1-',4,[{file,"src/couch_mrview_util.erl"},{line,1011}]},{couch_btree,'-write_node/3-lc$^0/1-0-',5,[{file,"src/couch_btree.erl"},{line,435}]},{couch_btree,'-write_node/3-lc$^0/1-0-',5,[{file,"src/couch_btree.erl"},{line,438}]}]}

[error] 2017-05-25T19:15:41.653424Z couchdb@localhost <0.23095.11> 6aa615c490 rexi_server throw:{<<"reduce_overflow_error">>,<<"Reduce output must shrink more rapidly: Current output: '[{\"linacTpsRequest_cid\":\"linac_tps_2015-03-13_14.46.37.287005_185313df929b11bd40cbdee210cff04a\",\"lin'... (first 100 of 441 bytes)">>} [{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,56}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,244}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[notice] 2017-05-25T19:15:41.653758Z couchdb@localhost <0.22178.11> 6aa615c490 localhost:5984 127.0.0.1 undefined GET /m3d_request/_design/mms.worker.request/_view/RequestKnownDbsQuery?reduce=true&group_level=2 500 ok 3008
```

## Steps to Reproduce (for bugs)

I have not verified the following manually, but:
- Create a design doc with two views, one normal with a sane reduce, and one with a reduce that just returns a 1kb string of text.
- Query the first view, get an error.
- The error should indicate that the problem is with the second view, but it currently does not.

## Context

I have design docs with ~15 views in some cases, and now I have to hunt through the code to find one that has a reduce that might output something matching:

`'[{"linacTpsRequest_cid":"linac_tps_2015-03-13_14.46.37.287005_185313df929b11bd40cbdee210cff04a","lin'... (first 100 of 441 bytes)`

**Comment by elistevens** [comment]
This is a similar issue to https://issues.apache.org/jira/browse/COUCHDB-2634?filter=-2

**Comment by wohali** [comment]
Hi Eli,

I don't see any straightforward way to implement this. The problem here is that all of the reduces in a design document are processed simultaneously, and all reductions within that ddoc are added together and contribute to the check for whether the reduce output is not shrinking rapidly enough. In other words, we don't know.

I might be able to enhance that error line with the name of the ddoc being processed, but that's the best I can do.

FYI post-2.0 that error check has been modified to be a bit more lenient and to produce a slightly different log message, see https://github.com/apache/couchdb/commit/3937fb1ef2cb4377571f488e7a20e003b5e8c69c and https://issues.apache.org/jira/browse/COUCHDB-3046 for the details. You could use the new `log` setting to get the detail you need to assist in debugging, though again by its very nature we still can't pinpoint the specific reduce function causing issues.

**Comment by elistevens** [comment]
Ah, I hadn't expected that implementation. Thanks for the link. I'm not 100% certain what `State.line_length` is, but I'm assuming it's the character length of all of the functions and data combined.

If that's true, this heuristic seems like it would trigger on literally every output if you had enough views in the design doc. Please check my logic:

Give a design doc 2k views, each with a reduce that is just `return values[0]`. Have all values just be `0`.

`reduce_line == "[" + "0," * 2047 + "0]"` which is 4097 characters long.

If all of the keys are unique, and we've got group=exact, then `input_length =  State.line_length - code_size` should be $HUGE - $HUGE leaving something about 4k in length as the input.

So `reduce_length` is 4097, and `input_length` is about the same, and it triggers every time.

Now I realize this is a pathological setup (2k views, etc.) but I think that it points to a weakness in the approach. What if the heuristic were implemented this way (I've removed the error checking for brevity):

```
for(var i = 0; i < reduceFuns.length; i++) {
    reductions[i] = reduceFuns[i](keys, values, rereduce);
    reduction_len = JSON.stringify(reductions[i]).length
    values_len = JSON.stringify(values).length
    if(values.length > 3 && reduction_len > values_len / Math.sqrt(values.length)) {
        // error out here
    }
}
```
I realize the re approach wastes the output of the `JSON.stringify` calls, but A) I don't know if that's relevant to performance, and B) it could probably be fixed.

**Comment by wohali** [comment]
That indeed will slow down view building for ddocs that have multiple views significantly, though I'd have to run numbers to prove it.

The fact is that a) 99% of views with reduces use built-ins, and b) increasingly CouchDB users are encouraged to separate views into multiple ddocs anyway, and c) in the 3.x timeframe we're hoping to replace SpiderMoney with a newer JS engine, running directly inside Erlang so I'm not sure there's a lot of appetite to fix this issue.

I'll leave the ticket open...just setting your expectations correctly that no one is going to burn a lot of cycles profiling this code just to generate a slightly improved error message here for <1% of our user base.

**Comment by elistevens** [comment]
That's a fair take on it. If it's truly a WONTFIX I don't mind the ticket getting closed. I think that's a more accurate representation of reality than treating it like "oh, nobody's gotten to it yet," when no one ever will.

I had apparently missed the memo about one-view-per-ddoc; changing to that is probably just a one-line change to the ViewQuery base class we've got, so I might go ahead and do that.

**Comment by wohali** [comment]
I want to be careful about saying it's a universal truth of one-view-per-ddoc. The main value in multiple views per design document is to control the amount of couchjs parallelism on your server (modulus the ini file setting to control the max. number of couchjs processes spawned at once). Move to a single-view-per-ddoc approach and on a busy DB that uses all views, for unbuilt views you can starve some views while they wait for a free couchjs process.

Generally for a machine 100% dedicated to CouchDB you want to target approximately (cores - 1) couchjs processes, so that would be the equivalent number of ddocs building at the same time.

If your views are largely prebuilt, the document churn in them is fairly static and the views don't need a lot of time to constantly build, # of ddocs has less of an impact. As always, performance test your specific situation to get the data you need - CouchDB's performance is very much data dependent. :)

**Comment by nickva** [comment]
Hi Eli,

You're right. That check is not perfect. It runs on the whole input line and whole output line. The input line includes both code for all the functions and the input values, and output includes all output values. But the check is currently mostly free. Your patch would work better and would perform the check for each function. But as Joan mentioned, it would take an extra stringify call. So I'd be inclined to keep the current implementation for that reason.

Think of it as a heuristic and with a handful of views per design doc it's usually clear which one misbehaves in practice.

**Comment by janl** [comment]
Let’s make this a wontfix for now as per [@wohali’s comment](https://github.com/apache/couchdb/issues/544#issuecomment-304432993).
