### ISSUE TITLE
304 after GET-PUT-GET cycle on a _show

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#559]
## Expected & Current Behaviour
1. Why is a GET-PUT-GET cycle returning a 304 on the second GET with headers "if-none-match" etag for a `_show`?

2. Misleading error message should be cleaned up

makefile output:
```
test/javascript/tests/show_documents.js                        
    Error: expected '304', got '304'
Trace back (most recent call first):
    
  52: test/javascript/test_setup.js
      T(false,"expected '304', got '304'","changed ddoc")
 326: test/javascript/couch_test_runner.js
      TNotEquals(304,304,"changed ddoc")
 296: test/javascript/tests/show_documents.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
      
[31mfail
```

couch.log:
```
[notice] 2017-05-31T23:29:00.503101Z node1@127.0.0.1 <0.16311.3> cea9c20ff0 127.0.0.1:15984 127.0.0.1 undefined GET /test_suite_db_xofwxqrc/_design/template/_show/just-name/78db53e02b06ddd067440cd0dd42f84c 304 ok 1
[notice] 2017-05-31T23:29:00.542915Z node1@127.0.0.1 <0.16311.3> 5cf1142bed 127.0.0.1:15984 127.0.0.1 undefined PUT /test_suite_db_xofwxqrc/_design%2Ftemplate 201 ok 40
[notice] 2017-05-31T23:29:00.545495Z node1@127.0.0.1 <0.16311.3> 58075015b3 127.0.0.1:15984 127.0.0.1 undefined GET /test_suite_db_xofwxqrc/_design/template/_show/just-name/78db53e02b06ddd067440cd0dd42f84c 304 ok 2
```

## Your Environment
Jenkins, Erlang 18.3

**Comment by wohali** [comment]
Through instrumentation of `ddoc_cache` and `ets_lru` I suspect that this is caused by cache eviction happening after the second `GET`. Here's a log from a failed instance of the test:

```
[notice] 2017-06-01T23:23:40.753022Z node1@127.0.0.1 <0.325.0> 6b133c86bb 127.0.0.1:15984 127.0.0.1 undefined GET /test_suite_db_hpsbou/_design/template/_show/just-name/ba144f667c0b6e26eb5f03b684033710 304 ok 3
[error] 2017-06-01T23:23:40.792726Z node1@127.0.0.1 <0.587.0> -------- ddoc_cache evicting _design/template
[error] 2017-06-01T23:23:40.793209Z node1@127.0.0.1 <0.587.0> -------- ddoc_cache evicted _design/template
[error] 2017-06-01T23:23:40.793479Z node1@127.0.0.1 <0.587.0> -------- ddoc_cache evicting _design/template
[error] 2017-06-01T23:23:40.793546Z node1@127.0.0.1 <0.587.0> -------- ddoc_cache evicted _design/template
[notice] 2017-06-01T23:23:40.794495Z node1@127.0.0.1 <0.325.0> dcca3621ed 127.0.0.1:15984 127.0.0.1 undefined PUT /test_suite_db_hpsbou/_design%2Ftemplate 201 ok 41
[error] 2017-06-01T23:23:40.795740Z node1@127.0.0.1 <0.391.0> -------- ets_lru remove test_suite_db_hpsbou
[error] 2017-06-01T23:23:40.796272Z node1@127.0.0.1 <0.325.0> 67dbdabbba ddoc_cache opening _design/template
[error] 2017-06-01T23:23:40.796338Z node1@127.0.0.1 <0.391.0> -------- ets_lru remove test_suite_db_hpsbou
[error] 2017-06-01T23:23:40.796350Z node1@127.0.0.1 <0.325.0> 67dbdabbba hit _design/template
[notice] 2017-06-01T23:23:40.798244Z node1@127.0.0.1 <0.325.0> 67dbdabbba 127.0.0.1:15984 127.0.0.1 undefined GET /test_suite_db_hpsbou/_design/template/_show/just-name/ba144f667c0b6e26eb5f03b684033710 304 ok 3
```

While I didn't instrument exactly where the GET occurs it's clear that it's fairly late, certainly after the `PUT 201` is returned, and likely after the subsequent `GET` actually reads from `ddoc_cache`.

During testing I also determined it's impossible to completely disable the `ddoc_cache`; I can only set its size to a positive integer. I'll submit a separate PR that fixes this. Once that change was implemented, and I could set `max_objects` to `0`, I ran the test in a loop 500 times and got not a single failure.

Our options are:
1. Change the `ddoc_cache` flush on updating a ddoc to be synchronous, not asynchronous, at least in the pathological case of a single node server. However, I am betting some Cloudant stakeholders will not want this (/cc @davisp @rnewson @nickva)
2. Improve our test harness to completely disable the `ddoc_cache` for this test, then use that option when running the test. This means augmenting `dev/run` and the JS harness so that we can specify `vm.args` files. Alternately, setup `ddoc_cache` with the appropriate `config:get` calls instead of using `application:get_env`.
3. Discard the single test under review (`test/javascript/tests/show_documents.js` lines 280-296) To me this is sweeping the issue under the rug, though if we are permanently changing the semantics here, it is marginally acceptable.
4. Drop ETag support for _shows.

**Comment by janl** [comment]
I’m generally weary of disabling tests, but I think it is warranted in this case.

1. This looks like a change that should have been marked as a BC break coming from 1.x to 2.x and I’d suggest we’d retroactively mark it as such. It would have been great to have found it earlier, but we made a conscious decision to keep some tests disabled i favour of getting 2.0 out the door. I’d make that trade-off again, but it is time to clean up now.

2. Disabling the cache for the test doesn't help anyone using this in production. This is adding and edge-case to the server to make tests pass, while the server default will be different. I don’t see how this is useful, when most people then would get the “broken” behaviour in practice. (That said, I’m +1ing [the proposed change to ddoc_cache](https://github.com/apache/couchdb/pull/561) so it *can* be disabled. This will be useful for debugging at least).

3. I can’t comment on ddoc_cache, but I could see that making that sync will cause all sorts of issues. It might even be impossible to do because of the CAP-nature of CouchDB, e.g. I think we would have to make ddoc_cache sync across all nodes in a cluster, and that’s not something we have the underlying mechanics for (nor do we want them, mostly).

4. This is a *very* niche feature that I don’t think many people depend upon. I believe we put this behaviour in when we were trying to advocate building web apps directly against CouchDB which we’ve largely moved away from.

As such, I’d suggest we:

1. delete the test in question from 2.x.
2. document this as a BC break for 1.x to 2.x (that we only discovered past 2.0).
3. get over our institutional aversion against the JS test suite, which time and time again finds real issues in CouchDB 2.x, and focus on getting all currently disabled JS tests enabled to flush out these issues.

**Comment by wohali** [comment]
In view queries other than `_show`s. a simple GET-PUT-GET cycle on a view could return the same result as this test case on a cluster, even without the ddoc_cache, though the exact same scenario as here could also recur. So I understand what you're saying here.

I will delete this test case and update the documentation to somehow reflect this change in behaviour. Thanks for the advice.

**Comment by davisp** [comment]
A fix for this test case without deleting it would be to add a synchronous eviction during the request to modify a design doc (on the client side so we're not blocking couch_db_updater). This way the one client that requested the modification should not see the pre-modified ddoc in the cache if they make another request.

Basically that'd be just a matter of making a ddoc_cache:evict_docs_sync or similar that uses gen_server:call/2 which would internally just use the same handle_cast code and reply with something arbitrary. And then we'd just add a couple lines in the clause at [1] that would look for any ddoc ids and do the eviction if they exist.

[1] https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db.erl#L1078

Also someone should remove this extra eviction code that's still hanging around because its a duplication of the code around line 315.

https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db_updater.erl#L902-L903

**Comment by wohali** [comment]
@davisp said on IRC:

```irc
15:55 <+davisp> Yeah, you're right. I was only thinking single node. The sync
                thing would still be async for other nodes so you're right that
                with the load balancer it'd break
15:55 <+davisp> Which makes this a tweak for tests which I agree isn't super
                awesome
15:55 <+davisp> So delete it!
```

Which is what I'm about to do, with an implicit +1 (so I will merge it straight away to master.)

**Comment by janl** [comment]
+1

**Comment by wohali** [comment]
Documented in https://github.com/apache/couchdb-documentation/commit/e274cea923a8e090c488970a931ae4852d0fc491
