### ISSUE TITLE
MRView's seq btree needs custom sorter function.

### ISSUE THREAD

**Issue by eiri** [apache/couchdb#592]
## Expected Behavior

During work on apache/couchdb#560 it was found that there are bug in mrview's seq btree leading to inconsistent behaviour on query with `since` parameter. 

It is expected that when querying `view_changes_since` we should get changes feed starting from _next_ update sequence than provided at `since`.

## Current Behavior

Response of `couch_mrview:view_changes_since/7` either include or exclude entry for `since` update sequence, depending on a view's key data type.

## Possible Solution

The issue here is that `seq_btree` using tuples`{UpdSeq, ViewKey}` as the keys and `ViewKey` can be any mapped from JSON data type: binary, integer or boolean. We are using erlang native collision to find first key to start from, so we can't construct consistent low limit key.

We need to specify custom `less` function on seq_btree creation and normalize keys in it.

## Steps to Reproduce (for bugs)

Since http end-point `/{db}/_design/{ddoc}/_view_changes` not exposed at the moment it's a bit hard to reproduce without changing existing `changes_since_test_ test` suite to create view with integer keys instead of binaries.

## Context

It's a low priority issue, the function in question not exposed to any interface.

**Comment by AlexanderKaraberov** [comment]
Hi @eiri  
I know that this is perhaps not a proper place to ask this question but I don't want to escalate and create a separate issue for a behaviour which just seems confusing to me and probably is not a bug at all.
So I have a document in the db which I delete either via `DELETE /db/doc?rev=1-aa` or via `PUT db/doc?rev=1-aa  -d "{_deleted":true}`. 
And now I want to "undelete" it via `PUT db/doc?rev=2-aa -d "{_deleted":false}"`. This was working fine in the CouchDB 1.x and is something what I'd expect to work in 2.x too, because when updating an existing document, the current document revision must be included in the document. But now in CouchDB 2.x I receive:
```
{"error":"conflict","reason":"Document update conflict."}
```
But this works fine if I'm not including document revision in the request for the case when I "undelete" the doc like this: `PUT db/doc -d "{_deleted":false}"`. So, the actual logic still works and I see all the corresponding revisions via `revs_info=true`. My question is this an expected behaviour? And if yes what were the reasons behind this? I think this has something to do with this logic inside of [update_docs/4](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db.erl#L1050)

**Comment by eiri** [comment]
@AlexanderKaraberov Ah, this happened before of my time, so it took a bit of digging through the old commits to see what's going on here.

Yes, this is an intentional change and it was done to address [this bug](https://issues.apache.org/jira/browse/COUCHDB-1415). Short version is that the previous version of `merge_rev_trees` relied on equality of the old rev tree and the merged rev tree in order to know when the update is a document recreation. If body of the deleted document been compacted away then at recreation you've been getting into situation when the old rev tree and the new rev tree different in content but identical in structure.

To address that `merge_rev_trees` was essentially rewritten completely in [this commit](https://github.com/apache/couchdb/commit/39df1d5e78a3ffd855cc9c2a6aa257237d4444da). So now when you are trying to recreate with `rev` you are ending up in [this codepath](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db_updater.erl#L589), because your rev's depth bigger than 1.

This is all a bit esoteric, so I hope it makes sense to you.

**Comment by eiri** [comment]
After discussion dev@ mail list we decided to just remove this implementation of view's changes and redoing it later from a scratch.

**Comment by AlexanderKaraberov** [comment]
@eiri , thank you for spending time and writing such a detailed write-up. 
Yeah, I got the logic behind this, and it makes sense.
