### ISSUE TITLE
Security objects cannot be synced if nodes are in maintenance mode

### ISSUE THREAD

**Issue by calonso** [apache/couchdb#602]
## Expected Behavior
On a running cluster, if one turns half of a particular shard's replicas into `maintenance_mode`, the cluster should keep working properly.

## Current Behavior
On a running cluster, if one turns half of a particular shard's replicas into `maintenance_mode`, **Error getting security objects for <<"affected_database_here">> : {error,no_majority}** begin to appear.

## Possible Solution
Allow the security objects sync internal process to *push through* maintenance mode.

## Context
I'm building a [CouchDB automatic administration toolset](https://github.com/cabify/couchdb-admin) and I was trying out different scenarios to see it working, in this case I was simulating an operation where on a database with two replicas per shard and one of them being down. I add a third node, put it into maintenance mode and make it replicate the particular shard. At that moment, majority cannot be achieved and the errors start arising.

## Your Environment
It is a Kubernetes managed cluster where the Docker image in use is [https://hub.docker.com/r/klaemo/couchdb/](https://hub.docker.com/r/klaemo/couchdb/)
* Version used: 2.0.0
* Link to your project: [https://github.com/cabify/couchdb-admin](https://github.com/cabify/couchdb-admin)

**Comment by kocolosk** [comment]
I'm wondering if we should allow the internal replicator to access security objects on shard replicas hosted by nodes in maintenance mode. That would have addressed the `no_majority` issue here and allowed for the security objects to be synced.

We don't see this issue in the "typical" case of an N=3 database hosted on a cluster with a single node in maintenance mode because we can still reach a quorum on the security object from the healthy copies, and the subsequent write request already "punches through" maintenance mode successfully.

**Comment by janl** [comment]
@kocolosk are you saying that you should only ever put as many nodes into maintenance mode as can be spared by quorum? If yes, then this could be a wontfix.

**Comment by kocolosk** [comment]
@janl no, that wasn't what I was suggesting; I was only explaining why this sort of thing tends to not crop up in production.

I'd agree that a user should not voluntarily put a majority of cluster nodes into maintenance, but if that user is unlucky enough to lose 2/3 of a cluster and she still wants predictable responses to view queries then she may well end up in this position.

I was suggesting setting a flag somewhere in the codepath of `mem3_sync_security` that would allow it to retrieve security objects from nodes in maintenance mode. One (slightly hacky) way to do that would be to set a custom IO priority for the request.

This is not without its own issues, though ... in the case I described above where 2/3 of the cluster was destroyed a sync process patched in this way could actually remove the security settings from the remaining healthy nodes, since the shards on the rebuilding nodes would constitute a simple majority of all database shards and "outvote" the healthy ones.

The proper fix here is to introduce versioning into security objects. I recall some attempts at doing so over the years but also recall those attempts running into unexpectedly gnarly corner cases. @davisp and @chewbranca may remember more.

**Comment by janl** [comment]
@kocolosk thanks for the clarification, and yeah, looks like we need to wait for [cassim](https://github.com/apache/couchdb-cassim) to make it into prod.

I’m gonna close this issue and link one from the cassim repo, so we remember this.

**Comment by manas86** [comment]
anyone has any solution for this? we have 2 out of 3 are in maintenance mode and one of DB showing no_majority error.

**Comment by wohali** [comment]
@manas86 Are you able to bring either of the 2 nodes out of maintenance mode temporarily?

**Comment by manas86** [comment]
@wohali At the moment we brought up 2 nodes and saved it, but this is not what I wanted. Will it be possible for CouchDB, allow the security objects sync internal process through other nodes are in maintenance mode?

**Comment by wohali** [comment]
@manas86 See above, that's what this ticket is tracking, though resolving the issue is not trivial.

https://github.com/apache/couchdb/issues/904

**Comment by manas86** [comment]
I could imagine, why it's not trivial. But would really help to do so.

**Comment by kripper** [comment]
We had a 2 nodes cluster.
One node died, so we added a new node to the cluster and renamed the node references in the shards.
CouchDB synchronized the shards to the new node, but the logs are full of `Bad security object in <<mydb>>` messages and the db permissions are wrong on the new node.
Any idea why security objects / permissions are not sync'ing correctly in this scenario?

Copying the /_security JSON from the old node to the new node (via GET + PUT) seems to fix the problem.

Are we doing something wrong here?
