### ISSUE TITLE
SSL / HTTPS settings lead to shards being shown, instead of databases.

### ISSUE THREAD

**Issue by vvasuki** [apache/couchdb#718]
The problem (observed in 2.0.0, and going [by the chat on slack](https://couchdb.slack.com/archives/C49LEE7NW/p1501169019494112?thread_ts=1501084518.687667&cid=C49LEE7NW), unlikely to change in the soon-to-be-released 2.1.0) is described in [this stackexchange post](https://stackoverflow.com/questions/41194127/couchdb-permissions-over-https) and [this bitnami thread](https://community.bitnami.com/t/https-config-disabled-database-list-messed-up/48668).

Copying over description from the bitnami post:

> When I log into Fauxton using HTTPS, if I go to "Configuration" it says "Config Disabled" at the top. If I log into with port "5984", I can make changes to the configuration. Is there a way to enable Config on the secured side?
> 
> I setup CouchDB as a single node, but in the HTTPS side of Fauxton I am getting a list of about 20 shard databases in the all dbs view that look like this: (I'm not listing all of them)
> shards/00000000-1fffffff/_global_changes.1492544140	This database failed to load.
> 
> The databases listed in the HTTP fauxton vs the HTTPS fauxton are not the same, if I create a DB in one, it does not show up in the other.
> 
> 

My environment: Ubuntu 16, Couchdb 2.0

**Comment by wohali** [comment]
Hi there @vvasuki , can you please share with us your `local.ini` file(s) and any other customizations you've made?

**Comment by vvasuki** [comment]
Hi @wohali , 

https://github.com/vedavaapi/vedavaapi-misc/tree/master/couchdb/etc has my effective configuration.

**Comment by wohali** [comment]
This was a documentation bug, addressed here:

https://github.com/apache/couchdb-documentation/commit/6cd1044e1813fc054da8f911fd39ed8215a5bba6

**Comment by wohali** [comment]
In case it's not clear:

```
[daemons]
httpsd = {chttpd, start_link, [https]}
```
is the right setting, and your bind is in the wrong place, it should be:
```
[chttpd]
bind_address = 0.0.0.0
```

**Comment by Richard-O-Wood** [comment]
I was having a very similar problem until earlier this morning. 
I am running V2.1.0 on Windows Server 2012 R2
I am using a WSSO_Proxy server for authentication.
However, I do have an OpenSSL certificate and CA installed and referenced in my local.ini

My Fauxton Databases page was working fine on HTTP (port 5984) but on HTTPS (port 6984) I was getting shards instead of my databases.  I read through the explanations from @wohali above, and tried a number of different combinations.  Finally got a local.ini file that would work.  I thought I would share my file for reference.  I changed a few things in the attached file for obfuscation purposes like the IP address company name in the URL and some characters in the hash values.  

Hopefully this will help someone else.
Also, if anyone spots something "wrong" in my local.ini, please let me know.

[local.ini](https://github.com/apache/couchdb/files/2398383/local_ini.txt)
