### ISSUE TITLE
XMLHttpRequest cannot load. No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by t0nylai** [apache/couchdb#805]
## Expected Behavior

Using Cross-Origin Resource Sharing(CORS), origins = * and credentials = true works in ver 2.0 but not allowed in ver 2.1. 

## Current Behavior

Looking for an alternative way using CORS in ver 2.1, origins = * and credentials = true. Same error if I keep  credentials = true and Origins =http://localhost, http://intranet-dev, http://intranet-qa  

## Possible Solution

Keep origins = * and credentials = true for CORS

## Steps to Reproduce (for bugs)

1 .local.ini, enable CORS in httpd, [CORS] origins = * and credentials = true
2. even I change Origins to my web server, http://localhost, http://intranet-dev, http://intranet-qa
3. same error and no idea what to do
4.

## Your Environment

* Version used: 2.1
* Browser Name and version: Chrome, Version 59.0.3071.115 
* Operating System and version (desktop or mobile): Windows Desktop,client: Windows 7, server: Windows 2008R2
* Link to your project:

**Comment by wohali** [comment]
Our CORS test passes so this is likely a misconfiguration of some sort. I am not familiar with the CORS support so I can't immediately help further. Can you paste your full local.ini file?

Our tests: https://github.com/apache/couchdb/blob/master/src/chttpd/test/chttpd_cors_test.erl

**Comment by t0nylai** [comment]
Hi Joan,

On CouchDB 2.0, I used to have origins = * and credentials = true  for
CORS.  In  ver 2.1, I see it doesn't allowed. So I have origins =
http://intranet-dev,http://intranet-qa

"couchdb2_1-dev" is a Windows 2008R2 machine where the Couchdb 2.1
installed and database located.
"intranet-dev" is a Windows 2008R2 IIS  web server has the application
running and access db on couchdb2_1-dev

I still have this error.
XMLHttpRequest cannot load http://couchdb2_1-dev/sash_dev/. Response to
preflight request doesn't pass access control check: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://intranet-dev' is therefore not allowed access. The response
had HTTP status code 401

Tony Lai

**Comment by rnewson** [comment]
hm, not me. @chewbranca maybe?

**Comment by wohali** [comment]
@t0nylai I've looked at the source code and there has literally been no change to the CORS support between 2.0 and 2.1, except for a single change to add max_age support, and another to add helper functions for hooks:

https://github.com/apache/couchdb/commit/0cfd56a6413b18f8970c69b90dfec675cf4c4b38
https://github.com/apache/couchdb/commit/4f80b40666d9ac77d4bca038eb7bdbe9a9ff3a84

* is still supported for origins, or should be.

I'm going to close this, because as far as I can tell there is no CouchDB bug here. If you have specific usage questions you can try our user@couchdb.apache.org mailing list, where I'm sure you'll find more people who use CORS in CouchDB.
