### ISSUE TITLE
Add support for queries in /{db}/_all_docs POST

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#820]
## Expected Behavior
I should be able to POST to `/{db}/_all_docs` and specify a `queries` list in the body, the same way I can do with a regular MapReduce view.

## Current Behavior
`"queries":[...]` is only supported in JS MapReduce views.

**Comment by jiangphcn** [comment]
Hi @wohali, what you do think that we only support "_all_docs" endpoint with this feature, or also need to support `_local_docs` and `_design_docs` endpoint as well?

**Comment by jiangphcn** [comment]
@wohali I added this support for
 - /{db}_all_docs 
 - /{db}/_design_docs
 - /{db}/_local_doc

in PR https://github.com/apache/couchdb/pull/1032

Would you please review them when you get back? (No hurry, and enjoy your break!)

**Comment by wohali** [comment]
Lookin' good @jiangphcn !

**Comment by iilyak** [comment]
This introduces a problem with API consistency. Because the response schema changes depending on what is POSTed. This makes it quite hard to interact with from static type languages.
It is unfortunate we merged it already. @wohali is it really needed? If so would you be ok if we move the implementation to separate endpoint?

**Comment by wohali** [comment]
@iilyak Go ahead and move it, we haven't released it yet.

If you move it, you're responsible for fixing the docs :)

**Comment by jiangphcn** [comment]
@wohali thanks for response. I will take care of codes and docs.

**Comment by iilyak** [comment]
Thank you @wohali

**Comment by iilyak** [comment]
@ricellis Which one is preferable in terms of support in libraries and OpenAPI Specification:
- `_all_docs/_query` / `_desing_docs/_query` / `_local_docs/_query`
- `_all_docs_query` / `_desing_docs_query` / `_local_docs_query`

**Comment by ricellis** [comment]
I think it doesn't matter much from a client side implementation perspective. I do think however that `_all_docs_query` etc may be preferable in that they avoid giving the impression that `_query` is an element of an `_all_docs` collection as it would be represented in a more typical REST style URI.

As an aside I do think a name like `_all_docs_query` is a confusing from the user perspective of potentially thinking it is related to the mango queries, but I can't really think of anything better, especially given the `queries` object that is sent in the `POST` body.

**Comment by wohali** [comment]
@ricellis I agree that `_all_docs_query` is confusing. `_all_docs/_query` is closer to how design documents work right now.

**Comment by iilyak** [comment]
@wohali: This issue originally was about `_all_docs` only. I have an implementation of new endpoints `_all_docs_view_query` / `_desing_docs_view_query` / `_local_docs_view_query` already.
However I am contemplating with the idea to remove `_desing_docs_view_query` and `_local_docs_view_query`. On the grounds that:
1. The issue was originally about `_all_docs` only. Which indicates that there is probably no immediate need for `_design_docs` and `_local_docs`
2. Adding 3 new endpoints is more verbose. Although the difference is 8 lines or so.
3. There are probably very few `_design` docs and user can use `_design_docs` endpoint directly to get them all and filter on client side.

**Comment by chewbranca** [comment]
Bubbling up some thoughts from an irc discussion about this with @wohali, @rnewson, and myself. It's worth noting that we already support the multi-queries approach in the `_view` API, so the functionality reverted in PR#1143 was actually consistent with existing API precedent. If folks feel strongly enough about separating out the multi query logic into dedicated API endpoints, I think it makes sense to do the same for views as well for consistency.

@rnewson pointed out an alternative option would be to use the `Content-Type` response header to declare the response body format. This would provide a deterministic way for static languages to understand the response body by what's declared in the headers. It could be ` x-vnd.couchdb.view vs x-vnd.couchdb.multi-query` or whatever.

**Comment by rnewson** [comment]
The (purported) problem with the _all_docs response is that the format of the response body requires knowledge of the request (whether the body had a {"queries": [...]} format or not). 

The mooted solution is to have different endpoints, but that has exactly the same problem. You have to know the associated request url.

Why is one better than the other?

**Comment by iilyak** [comment]
> Why is one better than the other?
1. With one to one mapping between request and response the client library for static language wouldn't need a factory pattern. For example `com.google.gson.JsonParser` for Java requires passing a POJO class to the `gson.fromJson` method. The call look like `gson.fromJson(entry.getValue(), MyPOJO.class);`. It is more complex when response mutate.
2. The API becoming expressible using OpenAPI Specification if the response structure is independent from:
  - posted content 
  - query parameters

There are quite a few interesting possibilities if we can express our API with OpenAPI Specification:
 - we can generate tests to check our input validation automatically
 - there are testing tools to ensure that there are no API changes (they work as MITM proxy). We can use this to make sure that:
   1) All APIs are documented in docs
   2) The API specification is in sync with implementation
   3) We are aware of incompatibilities between different versions of spec
 - we can generate some parts of libraries for different languages automatically
 - we can generate code to validate input data passed to endpoints
 - we can embed required access roles into spec in order to generate rules for `chttpd_auth_request`. Which simplifies security audit of the code. 
 - we can generate boilerplate code for endpoints if decide to switch to another http server.

However this is off topic and should be discussed in ML.

I am aware that there are few precedents in CouchDB which return different responses based on either posted data or query parameters.

**Comment by ricellis** [comment]
@chewbranca 
Yes, I'm aware of the support already existing in the `_view` API and if people want to match that behaviour I can live with it. I just thought it might be better to stem the flow of APIs not describable by OpenAPI if we can.

@rnewson 
The difference is in making something that *could* be described by the OpenAPI specification where the response schema is limited to being varied by the `path` or by the `content-type` - not other headers, query parameters, or body content.

Whilst a custom `Content-type` like `x-vnd.couchdb.view` would allow for different response schemas the downside would be missing out on automatic handling provided by using `application/json` (e.g. in auto-generated documentation with HTTP examples).

**Comment by rnewson** [comment]
Makes sense. 

If we do this, let’s add it for _view also. We can leave the dual support for _view itself for backward compatibility.

**Comment by wohali** [comment]
I'm really unhappy with the naming convention chosen here, but I acknowledge this is a bike-shedding point.

Are we really dead-set against this being a level down, i.e. `/{db}/_all_docs/_queries` or `/{db}/_design/{ddoc}/_view/{viewname}/_queries` ?

**Comment by ricellis** [comment]
If people generally prefer the `.../_queries` I'm fine with that because it still provides a unique path for the queries `POST` that returns the different response object schema.

**Comment by wohali** [comment]
@jiangphcn @ricellis @rnewson @iilyak Can we get this re-merged in please?

I have a +1 for using a `/_queries` endpoint but am fine with the previous proposal if that's where we're going.

2.2.0 approaches and I'd like this set of features to be in there. And +1 for @rnewson 's comment about adding this for `_view` and leaving the old endpoint for backward compatibility.

@jiangphcn also can you please revisit your open PRs on apache/couchdb-documentation, and update as necessary? Thank you!

/cc @janl asking before I add this to the 2.2.0 milestone. We have the code, we just need to agree on the endpoints involved.

**Comment by jiangphcn** [comment]
@wohali Hey Joan,  I am fine to re-merge the codes in PR https://github.com/apache/couchdb/pull/1032. Let us wait for next Monday to let everybody to check and raise concern if have. Otherwise, I can merge it next Tuesday (GMT+8). 

Also, thanks for your reminder. Furthermore, I will re-visit my documentation PRs for endpoint related code changes.

**Comment by javacodecreeks** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jiangphcn** [comment]
@iilyak @davisp @janl I just had some discussion with @wohali about next step to address this issue. 

Based on previous discussion, the proposed approach is to implement new endpoints to support queries, and this includes
 - /{db}/_all_docs/_queries
- /{db}/_all_docs/_queries
-  /{db}/_local_docs/_queries

In addition, for view, we implement new endpoint to support queries, and also keep original implementation for backward compatibility.
- _view/{viewname}/_queries

Please let us know in case you have any concern on this approach. 

cc @wohali @rnewson @ricellis @chewbranca

**Comment by davisp** [comment]
Isn't it `_design_docs` instead of `_all_design`? Otherwise that seems fine. queries seems a bit of an odd name but I haven't got anything immediately better. I would remove the `_` prefix from the queries path part though. The `_` prefix on the prior path part already suggests this is a system path so it seems odd to repeat it.

Otherwise that seems fine to me.

**Comment by wohali** [comment]
Agree with @davisp, so that'd make the full paths to the endpoints:

```
/{db}/_all_docs/queries
/{db}/_design_docs/queries
/{db}/_local_docs/queries
/{db}/_design/{ddoc}/_view/{viewname}/queries
```

We'll need to be careful with the documentation on the first and last ones.

We want to encourage use of this and mark the old endpoints as deprecated with appropriate pointers to the new endpoints. Since the endpoint isn't being removed *yet* we don't need the post to the mailing list:

> Whenever a change is proposed to a release branch or master that removes or changes an existing HTTP API endpoint in a way that breaks backwards compatibility with a released version of CouchDB, the proposed change must be announced on the developer mailing list, and a minimum of a lazy consensus decision is required.

The vote will come whenever we move towards a 3.0 release, and actually remove the old endpoints.

**Comment by davisp** [comment]
+1

**Comment by iilyak** [comment]
+1

**Comment by jiangphcn** [comment]
Based on current agreement, I drafted codes PR https://github.com/apache/couchdb/pull/1222 and documentation PR https://github.com/apache/couchdb-documentation/pull/241. Could somebody from you please review them? Thanks
