### ISSUE TITLE
Provide info=true and keys=[] arguments for /_all_dbs

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#822]
## Expected Behavior
Right now, if I want the database info for all databases on a server, I must individually access /{db} for each database. It'd be swell to make a single request to retrieve all of that.

While I'm at it, it'd be extra nice if I could also specify keys=[....] to select a subset of all databases on a server to monitor.

## Current Behavior
N requests must be made for N databases if info is to be retrieved on all databases.

**Comment by jiangphcn** [comment]
welcome back @wohali ! I created PR #1082 for this issue. Would you please like to review them? Thanks

**Comment by iilyak** [comment]
My 2¢

Accessing all databases on the server is expensive operation. Since get_db_info goes through `couch_server` process. For clusters with big number of databases opening all of them at the same time would cause a series of evictions from `couch_lru`. This in its turn causes lots of update_lru messages to couch_server. 

We could try to modify `couch_db:get_db_info` to open database in read only mode without using `couch_server`. However with this approach we wouldn't be able to return the same information as we currently do. Therefore we would have to introduce new endpoint. Which is a good thing since it would make it expressible in OpenAPI spec which we can benefit from latter on. 

Following keys are problematic:
  * update_seq
  * purge_seq
  * compact_running
  * instance_start_time
  * committed_update_seq
  * compacted_seq

**Comment by davisp** [comment]
@iilyak What's the issue with update_seq and purge_seq? Those are both in the header. I understand why the others are an issue.

Also I do understand the read-only approach, though I wonder if a "do-not-cache" option to couch_server:open might not also be a possibility here? Just spitballing on that front though.

**Comment by iilyak** [comment]
You are right on both fronts `update_seq` and `purge_seq` could be retrieved and `do-not-cache` approach might work.
