### ISSUE TITLE
Healthcheck endpoint authentication should be optional

### ISSUE THREAD

**Issue by calonso** [apache/couchdb#823]
## Expected Behavior
When setting `chttpd.require_valid_user = true`the healthcheck endpoint `/_up` should not be protected.

## Current Behavior
Setting `chttpd.require_valid_user = true` also makes `/_up` endpoint to be authenticated.

## Possible Solution
Either unprotect the `/_up` endpoint always, which doesn't sound like very dangerous as nothing but the health of the system is exposed there or make it configurable.

## Context
Currently some butt providers (Google in this case) don't allow credentials to be given to healthcheck configurations. Setting `chttpd.request_valid_user = true` is something very desirable as you enforce authentication all over the place, but you can't combine both in this case as healthchecks will fail if auth is enforced.

## Your Environment
* Version used: 2.1.0~trusty
* Browser Name and version: Doesn't apply
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by wohali** [comment]
The problem here is that `require_value_user` is performed during _authentication_ phase, whereas checking for permissions for `_up` is done as an `authorization` phase check. Authentication happens before authorization.

Right now, the authentication handlers are completely agnostic of the path of the request that comes in; introducing an exception to that flow duplicates the code in the authorization layer. If we're only ever going to allow access to `/_up` that's one thing, but if this ever needs to be extended for other endpoints, we'll be repeating ourselves, which could lead to inconsistent choices being made and increase the complexity of maintaining this code.

I'll look at doing a PR, but there's no guarantees it'll land unchallenged in the code.

**Comment by calonso** [comment]
Amazing, thanks!!

**Comment by wohali** [comment]
You can see that PR went off the rails, @calonso . Sorry about that. 

I'm scaling back my coding in 2018, so hopefully someone else will pick this issue up.
