### ISSUE TITLE
Max number of databases 

### ISSUE THREAD

**Issue by corporatepiyush** [apache/couchdb#851]
I wanted to use CouchDB multi-master capabilities with PouchDB in Mobile devices.

Our application will have few millions of mobile app customer.

Does it makes sense to create few millions of databases in CouchDB server and have them sync on per user basis ?

**Comment by janl** [comment]
A million dbs on a single cluster could become daunting eventually, but db-per-user allows you to horizontally scale things, so every 100k or so users can live on their own cluster, e.g. with a little but of HTTP routing magic in front.

Make sure to use q=1 for per-user-dbs, otherwise you’ll run out of resources within a single cluster too quickly.

All this assuming you do not have millions of users just yet, and are ramping up over time.
