### ISSUE TITLE
Some passwords show up in the logs

### ISSUE THREAD

**Issue by wyc** [apache/couchdb#897]
## Expected Behavior

Passwords shouldn't show up in the logs.

## Current Behavior

A password showed up in the logs: https://pastebin.com/rNSeTrtK

## Possible Solution

Hide the password from the logs, and investigate other occurrences.

## Steps to Reproduce (for bugs)

The steps here:
https://github.com/apache/couchdb/issues/896

## Context

Discovered during https://github.com/apache/couchdb/issues/896, but probably worth its own ticket.
```
171925 < wayne> https://pastebin.com/rNSeTrtK
171951 < wayne> and yikes, it looks like the password gets leaked in the logs
```
## Your Environment

* Version used: 2.1
* Browser Name and version: Chromium
* Operating System and version (desktop or mobile): Desktop
* Link to your project: N/A

**Comment by janl** [comment]
For the record, CouchDB has never guaranteed that no passwords would end up in logs. We’re trying, but no guarantees.

That said, the fix is fairly simple. The `notice` level log here https://github.com/apache/couchdb-setup/blob/master/src/setup.erl#L214 should really be a debug level log. Same for most of the other notices in there.

Wanna attempt a PR? This is the debug function: https://github.com/apache/couchdb/blob/master/src/couch_log/src/couch_log.erl#L30-L31

**Comment by wyc** [comment]
Thanks for your response. Sure, I think I can do this one.

**Comment by janl** [comment]
Closing in favour of https://github.com/apache/couchdb/pull/1439

**Comment by wohali** [comment]
#1439 hasn't landed yet, reopening until it does
