### ISSUE TITLE
Aggregate stats for all nodes

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#903]
Continuing from #810:

> Replications will uniformly pick one node in the cluster to run on which doesn't have to be the node which processed the document update request. To detect the crashed stats update would have to know which node to check for changes. I made this mistake so mentioning it here just in case. Perhaps there is a case there in general for aggregating stats for all nodes.

/cc @nickva

**Comment by nickva** [comment]
The 810 issue as related to replicator stats should be fixed in https://github.com/apache/couchdb/pull/2447.  Per replication job stats are persisted to checkpoint and then used for job initialization.

If we want a general stats aggregator for all nodes, it would be a larger design, involving creating a top level aggregator, possibly with custom aggregators, a new top level API and so on. Closing for now that scope is a bit larger than intended here.
