### ISSUE TITLE
Fix release build process tooling

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#908]
Currently, there are 3 problems with the RC and release build process that I'm aware of:

1. The Makefile functionality to diff a given RC against the last one is broken for RC1 (because there is no RC0 tag).
1. There is no easy way to bump the version number - you have to manually edit both `Makefile` and `rel/reltool.config`. See: https://github.com/apache/couchdb/pull/907 Sure would be nice to pull this from an env var or tag or something.
1. There's no equivalent of "make reltarball" that does roughly the same thing as "make rc" when you check out from a release tag (e.g. 2.1.0). This could be collapsed with "make rc" if it was assumed that all RCs have to be built from a proper git tag.

**Comment by triplem** [comment]
Just leaving my w$ here.

It is good practice to keep the current version in a file in the project (eg. version.mk), as examples see Java builds using Maven or Gradle. In Nodejs this is common practice as well.

 I guess that the version.mk should be used as this single source of truth for the version of couchDb.

This information could then be used in the Makefile to bump the version eg. by using a tools like https://github.com/peritus/bumpversion (python) or https://github.com/fsaintjacques/semver-tool (bash). Then this information should be used in the Makefile. No specific target for RC necessary then, just one to create the tarball. Some of the tools do tag the girls repository as well after a bump, so that the tags and releases in GitHub as well (which I think can be easily done in the Makefile as well). 

I have looked into the releng config but have to admit, that I do not have a clue on how to adopt the version in there. Probably via a parse/replace?

Does this help you already?

**Comment by wohali** [comment]
I mostly filed this ticket for myself, but if you wanted to submit a PR and join the team, feel free!

FYI what you suggest is what we do already; the current source of truth is `rel/reltool.config` and is leveraged by the Erlang build tool `rebar` to set the version number in the build process.

In general, our process works and doesn't need a complete rework. There's really only 3 specific small things I'm trying to address here:

1. The Makefile prints a convenience diff from the current RC to a previous RC. I'm not sure we need it, and was going to propose just dropping it.
1. The Makefile has a "quick hack" hard-coded version number that it uses solely for the naming of the release artefact. It should be pulling that number from `rel/reltool.config` or from a tag/branch-name on the source repo.
1. The `make reltarball` can do the same thing as above.

**Comment by janl** [comment]
> ; the current source of truth is rel/reltool.config

We also have version.mk, which is used by `Makefile` things that aren’t rebar.

**Comment by wohali** [comment]
Closed by #907:

> To bump the version number, you'll still need to modify both version.mk and rel/reltool.config. I'll update the release procedure with this info for now.

> The new command for building an RC, say RC2, is COUCH_RC=2 make dist. The [wiki page](https://cwiki.apache.org/confluence/display/COUCHDB/Release+Procedure) has been updated.
