### ISSUE TITLE
CentOS 7 $releasever is 7Server, so repo described in documentation will not work

### ISSUE THREAD

**Issue by detbetteegern** [apache/couchdb#956]
On:
http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

this repo is mentioned:
[bintray--apache-couchdb-rpm]
name=bintray--apache-couchdb-rpm
baseurl=http://apache.bintray.com/couchdb-rpm/el$releasever/$basearch/
gpgcheck=0
repo_gpgcheck=0
enabled=1

The repo will not work because releasever is "7Server", not just "7" for CentOS7.

**Comment by wohali** [comment]
We test this ourselves with CentOS 7 and it works just fine. You must be running RHEL which uses 7Server instead of 7.

Sounds like this can be resolved with a documentation fix since all you need to do is modify your repo.

Would you care to open a PR over on the apache/couchdb-documentation repository? Thanks!
