### ISSUE TITLE
update 2.1 to 2.1.1 on windows server 2012 

### ISSUE THREAD

**Issue by mohshraim** [apache/couchdb#990]
I did update the couchDB on windows server 2012
from version 2.1 to 2.1.1

to be clear i couldn't able to run the new setup so uninstall the old version and installed the new one.

after install if i enter the fauxton using localhost:// or using 127.0.0.1://    the databases list will be as on image
![screen shot 2017-11-14 at 1 04 56 am](https://user-images.githubusercontent.com/16401732/32754260-cb87d4a2-c8d8-11e7-9a8a-5762f439eb73.png)

if i enter the Fauxton from my public IP the database list look normal as old version

![screen shot 2017-11-14 at 1 08 15 am](https://user-images.githubusercontent.com/16401732/32754544-c90873ac-c8d9-11e7-8425-ba8e0a9a8f28.png)

it seems all the way i updated is wrong....
now i did uninstall it and install again and cant configure as a single node..
when enter http://127.0.0.1:5986/_utils/#/setup/singlenode
the javascript give me tow errors 
 http://127.0.0.1:5986/_membership  400 (Bad Request)
 http://127.0.0.1:5986/_cluster_setup 400 (Bad Request)

should i re install the previous version 2.1?
any suggestion?
Thanks for your help.

**Comment by wohali** [comment]
If you've already set it up as single node, you don't have to repeat the setup steps after the reinstall.

*Don't ever use the :5986 port for Fauxton.* Always use the :5984 port unless the instruction manual specifically tells you otherwise.

http://127.0.0.1:5984/_utils should look fine and your setup steps should be fine as well.
